repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
    -   id: clang-format
        args: [--style=file, -i]
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        args: [--in-place]
    -   id: cmake-lint
