repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [--style=file, -i]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]
      # - id: cmake-lint
      #  exclude: util/cmake/modules/integrations/scripts/run_clang_format.cmake
  # - repo: https://github.com/cmake-lint/cmake-lint
  #   rev: 1.4.2
  #   hooks:
  #     - id: cmakelint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-ast
      - id: check-xml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: util/
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [cmake]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: fix-encoding-pragma
      - id: fix-byte-order-marker
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture
        args: [util/]
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/sirosen/texthooks
    rev: 0.2.2
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes
      - id: forbid-bidi-controls
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.7.2
    hooks:
      - id: typos
        args: [--write-changes]
        exclude: modules/Common/lemons_core/localization/languages.cpp
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
  # - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  #   rev: 2.4.0
  #   hooks:
  #     - id: editorconfig-checker
ci:
  skip: [shellcheck]
