---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [--style=file, -i]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]

      # general
      - id: check-added-large-files
        args: [--maxkb=2000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [cmake]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

      # shell scripts
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: util/

      # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: debug-statements
      - id: fix-encoding-pragma

  # git
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/milin/gitown
    rev: v0.1.7
    hooks:
      - id: gitown

  # text and typos
  - repo: https://github.com/sirosen/texthooks
    rev: 0.2.2
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes
      - id: forbid-bidi-controls
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.8.5
    hooks:
      - id: typos
        args: [--write-changes]
        exclude: modules/Common/lemons_core/localization/languages.cpp

  # CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]
    # - id: cmake-lint
    #   exclude: util/cmake/modules/integrations/scripts/run_clang_format.cmake

  # YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0
    hooks:
      - id: check-github-workflows

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
        exclude: CHANGELOG.md

  # shell scripts
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: [--tab]

  # Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [-i]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker

ci:
  skip: [shellcheck, gitown]
