Lemons: lemons::plugin::MetaParameter< ValueType > Class Template Reference
lemons::plugin::MetaParameter< ValueType > Class Template Reference
Plugins » lemons_plugin » Parameters » Meta parameters
A meta parameter class that implements the MetaParameterBase interface.
Public Types
using ParameterValueType = ValueType
The parameter's value type is publicly accessible through this typedef.
Public Member Functions
MetaParameter (const ParameterList &parameterListToUse, ValueType minimum, ValueType maximum, ValueType defaultValue, const String &paramName, ValToStringFunc< ValueType > stringFromValue=nullptr, StringToValFunc< ValueType > valueFromString=nullptr, const String &paramLabel={}, bool isAutomatable=true, ParameterCategory parameterCategory=ParameterCategory::genericParameter)
Creates a meta parameter.
MetaParameter (const ParameterTraits &traits, const ParameterList &parameterListToUse)
Creates a meta parameter from a ParameterTraits object.
void applyAllConnections () const
Applies the meta parameter's current value to all of its connections.
void createOrEditConnection (Parameter &parameter, float minAmt, float maxAmt)
Creates or edits a connection to a given parameter.
ValueType get () const noexcept
Returns the parameter's current value.
ValueType getDefault () const noexcept
Returns the parameter's current default value.
float getDenormalizedValue () const noexcept
Returns the parameter's current value, in the parameter's denormalized range.
ValueType getMaximum () const noexcept
Returns the maximum possible value for this parameter.
ValueType getMinimum () const noexcept
Returns the minimum possible value for this parameter.
const ParameterRange & getNormalisableRange () const final
Returns this parameter's range object.
float getNormalizedValue () const noexcept
Returns the parameter's current value, in a normalized 0-1 range.
ParameterTraits getParameterTraits () const final
Returns a ParameterTraits object representing this parameter.
String getStringForCurrentValue (int maxLength=50) const
Returns a textual description of the parameter's current value.
String getStringForValue (ValueType value, int maxLength=50) const
Returns a textual description for a parameter value.
ValueType getValueForString (const String &string) const
Converts some user input text to a possible representation as a parameter value.
bool hasConnection (const Parameter &parameter) const
Returns true if this meta parameter is currently connected to the given parameter.
bool isAutomatable () const final
Returns true if this parameter is automatable by the user's DAW.
bool isMetaParameter () const final
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
void loadConnectionsFromValueTree (const ValueTree &tree)
Recreates the state of a saved set of connections.
void loadFromValueTree (const ValueTree &tree) override
Loads the state of this meta parameter from a ValueTree.
bool removeConnection (const Parameter &parameter)
Removes the connection to the given parameter, if any.
ValueTree saveConnectionsToValueTree () const
Saves the state of this meta parameter's connections to a ValueTree.
ValueTree saveToValueTree () const override
Saves the state of this meta parameter to a ValueTree.
void set (ValueType newValue)
Sets the parameter's value.
void setDefault (ValueType newDefault)
Sets the parameter's default value.
void setDenormalizedValue (float value)
Sets the parameter's value, in the parameter's denormalized range.
void setNormalizedValue (float value)
Sets the parameter's value, in a normalized 0-1 range.
parameter_gesture_state Functions for gesture state
void beginGesture ()
Begins a change gesture for this parameter.
void endGesture ()
Ends any active change gesture for this parameter.
bool isChanging () const noexcept
Returns true if this parameter is currently in the middle of a change gesture.
parameter_midi_cc_mapping Functions for MIDI controller mapping
int getMidiControllerNumber () const noexcept
Returns the number of the MIDI controller mapped to this parameter, or -1 if this parameter is unmapped.
bool isMidiControllerMapped () const noexcept
Returns true if this parameter is currently mapped to a MIDI controller.
void setMidiControllerNumber (int newControllerNumber)
Maps this parameter to listen for changes in a specified MIDI controller number.
void removeMidiControllerMapping () noexcept
Removes the MIDI controller mapping, if any.
bool processNewControllerMessage (int controllerNumber, int controllerValue)
Call this function with each MIDI CC message your plugin receives, and the Parameter class will automatically update itself with changes in the appropriate controller, if a mapping is active.
parameter_default_value Functions related to the default value
void refreshDefault ()
Sets the parameter's current value as the default value.
void resetToDefault ()
Resets the parameter to the saved default value.
float getNormalizedDefault () const noexcept
Returns the parameter's default value, in a normalized 0-1 range.
float getDenormalizedDefault () const noexcept
Returns the parameter's default value, in the parameter's denormalized range.
void setNormalizedDefault (float value)
Sets the parameter's default, in a normalized 0-1 range.
void setDenormalizedDefault (float value)
Sets the parameter's default, in the parameter's denormalized range.
parameter_to_and_from_text Functions for converting to/from text
String getTextForNormalizedValue (float value) const
Returns a textual description of a normalized value in the range 0-1.
String getTextForDenormalizedValue (float value) const
Returns a textual description of a value in the parameter's denormalized range.
String getTextForCurrentValue () const
Returns a textual representation of the parameter's current value.
String getTextForMax () const
Returns a textual description of the parameter's maximum value.
String getTextForMin () const
Returns a textual description of the parameter's minimum value.
Static Public Attributes
static constexpr auto id_prop = "id"
static constexpr auto valueTreeType = "Connections"
Protected Member Functions
float denormalize (float input) const noexcept
Denormalizes the passed value using the parameter's NormalisableRange object.
float normalize (float input) const noexcept
Normalizes the passed value using the parameter's NormalisableRange object.
Static Protected Attributes
static constexpr auto controller_prop = "controllerNumber"
static constexpr auto default_prop = "default"
static constexpr auto value_prop = "value"
static constexpr auto valueTreeType = "PARAM"
Detailed Description
template<typename ValueType>
class lemons::plugin::MetaParameter< ValueType >
A meta parameter class that implements the MetaParameterBase interface.
See also
MetaParameterBase, TypedParameter
Member Typedef Documentation
ParameterValueType
template<typename ValueType > using lemons::plugin::TypedParameter< ValueType >::ParameterValueType = ValueType inherited
The parameter's value type is publicly accessible through this typedef.
Constructor & Destructor Documentation
MetaParameter() [1/2]
template<typename ValueType > lemons::plugin::MetaParameter< ValueType >::MetaParameter (const ParameterList & parameterListToUse, ValueType minimum, ValueType maximum, ValueType defaultValue, const String & paramName, ValToStringFunc< ValueType > stringFromValue = nullptr, StringToValFunc< ValueType > valueFromString = nullptr, const String & paramLabel = {}, bool isAutomatable = true, ParameterCategory parameterCategory = ParameterCategory::genericParameter) explicit
Creates a meta parameter.
Parameters
parameterListToUse The parameter list for this meta parameter to use to rebuild its connections when loading state.
minimum The minimum value the parameter can have.
maximum The maximum value the parameter can have.
defaultValue The initial default value for the parameter.
paramName The name of this parameter.
stringFromValue An optional lambda function that converts this parameter's value to a text description.
valueFromString An optional lambda function that converts a text input string to a value for this parameter.
paramLabel An optional label to use for this parameter's units.
isAutomatable Boolean flag that indicates whether this parameter should be automatable in the user's DAW.
parameterCategory An optional parameter category. See juce::AudioProcessorParameter::Category.
MetaParameter() [2/2]
template<typename ValueType > lemons::plugin::MetaParameter< ValueType >::MetaParameter (const ParameterTraits & traits, const ParameterList & parameterListToUse) explicit
Creates a meta parameter from a ParameterTraits object.
Member Function Documentation
applyAllConnections()
void lemons::plugin::MetaParameterBase::applyAllConnections () const inherited
Applies the meta parameter's current value to all of its connections.
beginGesture()
void lemons::plugin::Parameter::beginGesture () inherited
Begins a change gesture for this parameter.
createOrEditConnection()
void lemons::plugin::MetaParameterBase::createOrEditConnection (Parameter & parameter, float minAmt, float maxAmt) inherited
Creates or edits a connection to a given parameter.
If a connection to the given parameter already exists, it will be remapped to the new min & max amounts; otherwise, a new connection will be created. The min and max values should be between 0.f and 1.f, and can be thought of as the percent effect this meta parameter will have on this parameter.
denormalize()
float lemons::plugin::Parameter::denormalize (float input) const protected noexcept inherited
Denormalizes the passed value using the parameter's NormalisableRange object.
Referenced by lemons::plugin::Parameter::getDenormalizedDefault(), and lemons::plugin::Parameter::getDenormalizedValue().
endGesture()
void lemons::plugin::Parameter::endGesture () inherited
Ends any active change gesture for this parameter.
get()
template<typename ValueType > ValueType lemons::plugin::TypedParameter< ValueType >::get () const noexcept inherited
Returns the parameter's current value.
getDefault()
template<typename ValueType > ValueType lemons::plugin::TypedParameter< ValueType >::getDefault () const noexcept inherited
Returns the parameter's current default value.
getDenormalizedDefault()
float lemons::plugin::Parameter::getDenormalizedDefault () const noexcept inherited
Returns the parameter's default value, in the parameter's denormalized range.
See also
getNormalizedDefault()
References lemons::plugin::Parameter::denormalize(), and lemons::plugin::Parameter::getNormalizedDefault().
getDenormalizedValue()
float lemons::plugin::Parameter::getDenormalizedValue () const noexcept inherited
Returns the parameter's current value, in the parameter's denormalized range.
See also
getNormalizedValue()
References lemons::plugin::Parameter::denormalize().
getMaximum()
template<typename ValueType > ValueType lemons::plugin::TypedParameter< ValueType >::getMaximum () const noexcept inherited
Returns the maximum possible value for this parameter.
getMidiControllerNumber()
int lemons::plugin::Parameter::getMidiControllerNumber () const noexcept inherited
Returns the number of the MIDI controller mapped to this parameter, or -1 if this parameter is unmapped.
getMinimum()
template<typename ValueType > ValueType lemons::plugin::TypedParameter< ValueType >::getMinimum () const noexcept inherited
Returns the minimum possible value for this parameter.
getNormalisableRange()
const ParameterRange & lemons::plugin::Parameter::getNormalisableRange () const final inherited
Returns this parameter's range object.
getNormalizedDefault()
float lemons::plugin::Parameter::getNormalizedDefault () const noexcept inherited
Returns the parameter's default value, in a normalized 0-1 range.
See also
getDenormalizedDefault()
Referenced by lemons::plugin::Parameter::getDenormalizedDefault(), lemons::plugin::Parameter::refreshDefault(), and lemons::plugin::Parameter::resetToDefault().
getNormalizedValue()
float lemons::plugin::Parameter::getNormalizedValue () const noexcept inherited
Returns the parameter's current value, in a normalized 0-1 range.
See also
getDenormalizedValue()
getParameterTraits()
template<typename ValueType > ParameterTraits lemons::plugin::TypedParameter< ValueType >::getParameterTraits () const final virtual inherited
Returns a ParameterTraits object representing this parameter.
Reimplemented from lemons::plugin::Parameter.
getStringForCurrentValue()
template<typename ValueType > String lemons::plugin::TypedParameter< ValueType >::getStringForCurrentValue (int maxLength = 50) const inherited
Returns a textual description of the parameter's current value.
getStringForValue()
template<typename ValueType > String lemons::plugin::TypedParameter< ValueType >::getStringForValue (ValueType value, int maxLength = 50) const inherited
Returns a textual description for a parameter value.
getTextForCurrentValue()
String lemons::plugin::Parameter::getTextForCurrentValue () const inherited
Returns a textual representation of the parameter's current value.
getTextForDenormalizedValue()
String lemons::plugin::Parameter::getTextForDenormalizedValue (float value) const inherited
Returns a textual description of a value in the parameter's denormalized range.
See also
getTextForNormalizedValue()
References lemons::plugin::Parameter::getTextForNormalizedValue(), and lemons::plugin::Parameter::normalize().
Referenced by lemons::plugin::Parameter::getTextForMax(), and lemons::plugin::Parameter::getTextForMin().
getTextForMax()
String lemons::plugin::Parameter::getTextForMax () const inherited
Returns a textual description of the parameter's maximum value.
See also
getTextForMin()
References lemons::plugin::Parameter::getTextForDenormalizedValue().
getTextForMin()
String lemons::plugin::Parameter::getTextForMin () const inherited
Returns a textual description of the parameter's minimum value.
See also
getTextForMax()
References lemons::plugin::Parameter::getTextForDenormalizedValue().
getTextForNormalizedValue()
String lemons::plugin::Parameter::getTextForNormalizedValue (float value) const inherited
Returns a textual description of a normalized value in the range 0-1.
See also
getTextForDenormalizedValue()
Referenced by lemons::plugin::Parameter::getTextForDenormalizedValue().
getValueForString()
template<typename ValueType > ValueType lemons::plugin::TypedParameter< ValueType >::getValueForString (const String & string) const inherited
Converts some user input text to a possible representation as a parameter value.
hasConnection()
bool lemons::plugin::MetaParameterBase::hasConnection (const Parameter & parameter) const inherited
Returns true if this meta parameter is currently connected to the given parameter.
isAutomatable()
bool lemons::plugin::Parameter::isAutomatable () const final inherited
Returns true if this parameter is automatable by the user's DAW.
isChanging()
bool lemons::plugin::Parameter::isChanging () const noexcept inherited
Returns true if this parameter is currently in the middle of a change gesture.
isMetaParameter()
bool lemons::plugin::Parameter::isMetaParameter () const final inherited
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
isMidiControllerMapped()
bool lemons::plugin::Parameter::isMidiControllerMapped () const noexcept inherited
Returns true if this parameter is currently mapped to a MIDI controller.
loadConnectionsFromValueTree()
void lemons::plugin::MetaParameterBase::loadConnectionsFromValueTree (const ValueTree & tree) inherited
Recreates the state of a saved set of connections.
See also
saveConnectionsToValueTree()
loadFromValueTree()
template<typename ValueType > void lemons::plugin::MetaParameter< ValueType >::loadFromValueTree (const ValueTree & tree) override virtual
Loads the state of this meta parameter from a ValueTree.
Reimplemented from lemons::plugin::TypedParameter< ValueType >.
normalize()
float lemons::plugin::Parameter::normalize (float input) const protected noexcept inherited
Normalizes the passed value using the parameter's NormalisableRange object.
Referenced by lemons::plugin::Parameter::getTextForDenormalizedValue(), lemons::plugin::Parameter::setDenormalizedDefault(), and lemons::plugin::Parameter::setDenormalizedValue().
processNewControllerMessage()
bool lemons::plugin::Parameter::processNewControllerMessage (int controllerNumber, int controllerValue) inherited
Call this function with each MIDI CC message your plugin receives, and the Parameter class will automatically update itself with changes in the appropriate controller, if a mapping is active.
Returns
True if this parameter is mapped to the passed controller number.
refreshDefault()
void lemons::plugin::Parameter::refreshDefault () inherited
Sets the parameter's current value as the default value.
References lemons::plugin::Parameter::getNormalizedDefault(), and lemons::plugin::Parameter::setNormalizedDefault().
removeConnection()
bool lemons::plugin::MetaParameterBase::removeConnection (const Parameter & parameter) inherited
Removes the connection to the given parameter, if any.
Returns
True if a connection previously existed to the given parameter
removeMidiControllerMapping()
void lemons::plugin::Parameter::removeMidiControllerMapping () noexcept inherited
Removes the MIDI controller mapping, if any.
References lemons::plugin::Parameter::setMidiControllerNumber().
resetToDefault()
void lemons::plugin::Parameter::resetToDefault () inherited
Resets the parameter to the saved default value.
References lemons::plugin::Parameter::getNormalizedDefault(), and lemons::plugin::Parameter::setNormalizedValue().
saveConnectionsToValueTree()
ValueTree lemons::plugin::MetaParameterBase::saveConnectionsToValueTree () const inherited
Saves the state of this meta parameter's connections to a ValueTree.
See also
loadConnectionsFromValueTree()
saveToValueTree()
template<typename ValueType > ValueTree lemons::plugin::MetaParameter< ValueType >::saveToValueTree () const override virtual
Saves the state of this meta parameter to a ValueTree.
Reimplemented from lemons::plugin::TypedParameter< ValueType >.
set()
template<typename ValueType > void lemons::plugin::TypedParameter< ValueType >::set (ValueType newValue) inherited
Sets the parameter's value.
setDefault()
template<typename ValueType > void lemons::plugin::TypedParameter< ValueType >::setDefault (ValueType newDefault) inherited
Sets the parameter's default value.
setDenormalizedDefault()
void lemons::plugin::Parameter::setDenormalizedDefault (float value) inherited
Sets the parameter's default, in the parameter's denormalized range.
See also
setNormalizedDefault()
References lemons::plugin::Parameter::normalize(), and lemons::plugin::Parameter::setNormalizedDefault().
setDenormalizedValue()
void lemons::plugin::Parameter::setDenormalizedValue (float value) inherited
Sets the parameter's value, in the parameter's denormalized range.
See also
setNormalizedValue()
References lemons::plugin::Parameter::normalize(), and lemons::plugin::Parameter::setNormalizedValue().
setMidiControllerNumber()
void lemons::plugin::Parameter::setMidiControllerNumber (int newControllerNumber) inherited
Maps this parameter to listen for changes in a specified MIDI controller number.
Referenced by lemons::plugin::Parameter::removeMidiControllerMapping().
setNormalizedDefault()
void lemons::plugin::Parameter::setNormalizedDefault (float value) inherited
Sets the parameter's default, in a normalized 0-1 range.
See also
setDenormalizedDefault()
Referenced by lemons::plugin::Parameter::refreshDefault(), and lemons::plugin::Parameter::setDenormalizedDefault().
setNormalizedValue()
void lemons::plugin::Parameter::setNormalizedValue (float value) inherited
Sets the parameter's value, in a normalized 0-1 range.
See also
setDenormalizedValue()
Referenced by lemons::plugin::Parameter::resetToDefault(), and lemons::plugin::Parameter::setDenormalizedValue().
Member Data Documentation
controller_prop
constexpr auto lemons::plugin::Parameter::controller_prop = "controllerNumber" static protected inherited
default_prop
constexpr auto lemons::plugin::Parameter::default_prop = "default" static protected inherited
id_prop
constexpr auto lemons::plugin::Parameter::id_prop = "id" static constexpr inherited
value_prop
constexpr auto lemons::plugin::Parameter::value_prop = "value" static protected inherited
valueTreeType [1/2]
constexpr auto lemons::plugin::Parameter::valueTreeType = "PARAM" static constexpr protected inherited
valueTreeType [2/2]
constexpr auto lemons::plugin::MetaParameterBase::valueTreeType = "Connections" static constexpr inherited
The documentation for this class was generated from the following file:
MetaParameter.h