Lemons: lemons::music::Interval Class Reference
lemons::music::Interval Class Reference final
A class that represents a musical interval between two pitches.
Public Types
enum class Quality {
Diminished , Minor , Major , Augmented ,
Perfect
}
Describes the quality of the interval.
Public Member Functions
constexpr Interval ()
Creates an interval representing a perfect unison.
constexpr Interval (const Interval &other) noexcept
Copy constructor.
constexpr Interval (int kindToUse, Quality qualityToUse) noexcept
Creates an interval with a specified kind and quality.
constexpr int getCents_EqualTemperament () const noexcept
Returns the number of cents this interval represents in equal temperament.
juce::Array< double > getCents_JustIntonation () const
Returns an array of possible cents values this interval can represent in just intonation, taking enharmonic spelling into account.
constexpr Interval getInverse () const noexcept
Returns the interval that is the inverse of this one, taking enharmonic spellings into account.
constexpr int getKind () const noexcept
Returns the kind of this interval as an integer.
String getKindAsString () const
Returns a string description of this interval's kind.
constexpr int getNumSemitones () const noexcept
Returns the number of semitones that this interval represents.
constexpr Quality getQuality () const noexcept
Returns the quality of this interval.
String getQualityAsString (bool useShort=false) const
Returns a string description of this interval's quality.
String getStringDescription (bool useShort=false) const
Returns a string description of this interval.
constexpr bool isEnharmonicTo (const Interval &other) const noexcept
Returns true if the two intervals represent the same number of semitones, regardless of their enharmonic spelling.
constexpr bool operator!= (const Interval &other) const noexcept
Returns true if the two intervals are not exactly equal.
constexpr Interval operator+ (const Interval &other) const noexcept
Adds another interval object to this one.
constexpr Interval operator+ (int semitonesToAdd) const noexcept
Adds a number of semitones to this interval.
constexpr Interval & operator++ () noexcept
Increments this interval by one semitone, preserving the kind by manipulating the quality where possible.
constexpr Interval operator- (const Interval &other) const noexcept
Subtracts another interval object from this one.
constexpr Interval operator- (int semitonesToSubtract) const noexcept
Subtracts a number of semitones from this interval.
constexpr Interval & operator-- () noexcept
Decrements this interval by one semitone, preserving the kind by manipulating the quality where possible.
constexpr bool operator< (const Interval &other) const noexcept
Returns true if this interval is semantically smaller than the other one, taking enharmonic spellings into account.
constexpr bool operator== (const Interval &other) const noexcept
Returns true if the two intervals are exactly equal – that is, have the same kind and quality.
constexpr bool operator> (const Interval &other) const noexcept
Returns true if this interval is semantically larger than the other one, taking enharmonic spellings into account.
Static Public Member Functions
static constexpr Interval fromNumSemitones (int semitones) noexcept
Creates an interval from a number of semitones.
static Interval fromPitches (const Pitch &pitch1, const Pitch &pitch2) noexcept
Creates an interval from the distance between two pitch objects.
static constexpr Interval fromPitches (int midiPitch1, int midiPitch2) noexcept
Creates an interval from the distance between two MIDI pitches.
static Interval fromStringDescription (const String &string)
Creates an interval from a string description of one.
Detailed Description
A class that represents a musical interval between two pitches.
This class is meant for intervals that are an octave or smaller, and that can be expressed as a whole number of semitones.
Member Enumeration Documentation
Quality
enum class lemons::music::Interval::Quality strong
Describes the quality of the interval.
Note that not all possible quality values are valid for every possible interval type; a "major fifth" or a "perfect third" do not exist.
Enumerator
Diminished
Minor
Major
Augmented
Perfect
Constructor & Destructor Documentation
Interval() [1/3]
constexpr lemons::music::Interval::Interval () constexpr
Creates an interval representing a perfect unison.
Interval() [2/3]
constexpr lemons::music::Interval::Interval (int kindToUse, Quality qualityToUse) explicit constexpr noexcept
Creates an interval with a specified kind and quality.
If the kind or quality parameters are invalid, an assertion will be thrown.
Parameters
kindToUse The kind of interval to create – 0 for unison, 2 for second, 3 for third, etc. Note that 1 is not a valid value, and values greater than 8 will be reduced to their equivalent intervals that are within one octave (ie, using the modulus operator).
qualityToUse The quality of interval to create.
Interval() [3/3]
constexpr lemons::music::Interval::Interval (const Interval & other) constexpr noexcept
Copy constructor.
Member Function Documentation
fromNumSemitones()
constexpr Interval lemons::music::Interval::fromNumSemitones (int semitones) static constexpr noexcept
Creates an interval from a number of semitones.
This uses reasonable defaults, always preferring major, minor, or perfect intervals when available instead of augmented or diminished.
References lemons::math::abs().
fromPitches() [1/2]
static Interval lemons::music::Interval::fromPitches (const Pitch & pitch1, const Pitch & pitch2) static noexcept
Creates an interval from the distance between two pitch objects.
fromPitches() [2/2]
constexpr Interval lemons::music::Interval::fromPitches (int midiPitch1, int midiPitch2) static constexpr noexcept
Creates an interval from the distance between two MIDI pitches.
fromStringDescription()
static Interval lemons::music::Interval::fromStringDescription (const String & string) static
Creates an interval from a string description of one.
The passed string can be a long or short description.
getCents_EqualTemperament()
constexpr int lemons::music::Interval::getCents_EqualTemperament () const constexpr noexcept
Returns the number of cents this interval represents in equal temperament.
References getNumSemitones().
getCents_JustIntonation()
juce::Array< double > lemons::music::Interval::getCents_JustIntonation () const
Returns an array of possible cents values this interval can represent in just intonation, taking enharmonic spelling into account.
References Major.
getInverse()
constexpr Interval lemons::music::Interval::getInverse () const constexpr noexcept
Returns the interval that is the inverse of this one, taking enharmonic spellings into account.
An interval and its inverse add together to form a perfect octave – for example, a major second's inverse is a minor seventh, a perfect fourth's inverse is a perfect fifth, etc.
References Augmented, Diminished, getNumSemitones(), Major, Minor, and Perfect.
getKind()
constexpr int lemons::music::Interval::getKind () const constexpr noexcept
Returns the kind of this interval as an integer.
0 represents unison, 2 is a second, 3 is a third, etc.
getKindAsString()
String lemons::music::Interval::getKindAsString () const
Returns a string description of this interval's kind.
getNumSemitones()
constexpr int lemons::music::Interval::getNumSemitones () const constexpr noexcept
Returns the number of semitones that this interval represents.
References Augmented, Diminished, Major, Minor, and Perfect.
Referenced by getCents_EqualTemperament(), and getInverse().
getQuality()
constexpr Interval::Quality lemons::music::Interval::getQuality () const constexpr noexcept
Returns the quality of this interval.
getQualityAsString()
String lemons::music::Interval::getQualityAsString (bool useShort = false) const
Returns a string description of this interval's quality.
getStringDescription()
String lemons::music::Interval::getStringDescription (bool useShort = false) const
Returns a string description of this interval.
Parameters
useShort When true, a shorthand version of the description will be returned – for example, "M2" instead of "Major second", etc.
isEnharmonicTo()
constexpr bool lemons::music::Interval::isEnharmonicTo (const Interval & other) const constexpr noexcept
Returns true if the two intervals represent the same number of semitones, regardless of their enharmonic spelling.
operator!=()
constexpr bool lemons::music::Interval::operator!= (const Interval & other) const constexpr noexcept
Returns true if the two intervals are not exactly equal.
Note that this will return true for intervals that represent the same number of semitones but are spelled differently.
See also
isEnharmonicTo()
operator+() [1/2]
constexpr Interval lemons::music::Interval::operator+ (const Interval & other) const constexpr noexcept
Adds another interval object to this one.
See also
fromNumSemitones()
operator+() [2/2]
constexpr Interval lemons::music::Interval::operator+ (int semitonesToAdd) const constexpr noexcept
Adds a number of semitones to this interval.
See also
fromNumSemitones()
operator++()
constexpr Interval & lemons::music::Interval::operator++ () constexpr noexcept
Increments this interval by one semitone, preserving the kind by manipulating the quality where possible.
For example, a major second will increment to an augmented second, rather than a minor third.
References Augmented, Diminished, Major, Minor, and Perfect.
operator-() [1/2]
constexpr Interval lemons::music::Interval::operator- (const Interval & other) const constexpr noexcept
Subtracts another interval object from this one.
See also
fromNumSemitones()
operator-() [2/2]
constexpr Interval lemons::music::Interval::operator- (int semitonesToSubtract) const constexpr noexcept
Subtracts a number of semitones from this interval.
See also
fromNumSemitones()
operator--()
constexpr Interval & lemons::music::Interval::operator-- () constexpr noexcept
Decrements this interval by one semitone, preserving the kind by manipulating the quality where possible.
For example, a minor second will decrement to a diminished second, rather than a perfect unison.
References Augmented, Diminished, Major, Minor, and Perfect.
operator<()
constexpr bool lemons::music::Interval::operator< (const Interval & other) const constexpr noexcept
Returns true if this interval is semantically smaller than the other one, taking enharmonic spellings into account.
For example, this will tell you that an augmented fourth is "smaller" than a diminished fifth.
operator==()
constexpr bool lemons::music::Interval::operator== (const Interval & other) const constexpr noexcept
Returns true if the two intervals are exactly equal – that is, have the same kind and quality.
Note that this will return false for intervals that represent the same number of semitones but are spelled differently.
See also
isEnharmonicTo()
operator>()
constexpr bool lemons::music::Interval::operator> (const Interval & other) const constexpr noexcept
Returns true if this interval is semantically larger than the other one, taking enharmonic spellings into account.
For example, this will tell you that a diminished fifth is "larger" than an augmented fourth.
The documentation for this class was generated from the following files:
Interval.h
Interval_impl.h