Lemons: lemons::music::scales::KeySignature Class Reference
lemons::music::scales::KeySignature Class Reference final
Public Types
enum class Type { Major , NaturalMinor , HarmonicMinor }
Public Member Functions
constexpr KeySignature () noexcept
Creates a key signature object representing C major.
constexpr KeySignature (const KeySignature &other) noexcept
constexpr KeySignature (int numSharpsOrFlats, bool isSharps, Type typeToUse) noexcept
constexpr KeySignature (Type typeToUse, bool isSharps, int pitchClassOfRoot) noexcept
constexpr KeySignature (Type typeToUse, int pitchClassOfRoot) noexcept
bool containsPitch (const Pitch &pitch) const
bool containsPitch (int midiNoteNumber) const
bool containsPitchClass (int pitchClass) const
KeySignature getDominantKey () const noexcept
KeySignature getEnharmonicKey () const noexcept
juce::Array< Interval > getIntervals () const
juce::Array< int > getIntervalsAsSemitones () const final
constexpr int getNumFlats () const noexcept
constexpr int getNumSharps () const noexcept
KeySignature getParallelKey () const noexcept
juce::Array< int > getPitchClasses () const
int getPitchClassOfRoot () const noexcept final
int getPitchClassOfScaleDegree (int scaleDegree) const noexcept
juce::Array< Pitch > getPitches (int lowestMidiNote, int highestMidiNote) const
juce::Array< Pitch > getPitches (int octaveNumber) const
KeySignature getRelativeKey () const noexcept
Pitch getRoot (int octaveNumber) const noexcept
String getRootAsString () const noexcept final
String getScaleDegreeAsString (int scaleDegree) const noexcept final
String getStringDescription () const final
bool hasEnharmonicKey () const noexcept
bool isDominantKeyOf (const KeySignature &other) const noexcept
bool isEnharmonicKeyOf (const KeySignature &other) const noexcept
constexpr bool isFlatKey () const noexcept
constexpr bool isMajorKey () const noexcept
constexpr bool isMinorKey () const noexcept
bool isParallelKeyOf (const KeySignature &other) const noexcept
constexpr bool isRelativeKeyOf (const KeySignature &other) const noexcept
constexpr bool isSharpKey () const noexcept
int notesPerOctave () const noexcept final
constexpr bool operator!= (const KeySignature &other) const noexcept
bool operator!= (const Scale &other) const
constexpr bool operator== (const KeySignature &other) const noexcept
bool operator== (const Scale &other) const
Static Public Member Functions
static KeySignature fromStringDescription (const String &description)
Member Enumeration Documentation
Type
enum class lemons::music::scales::KeySignature::Type strong
Enumerator
Major
NaturalMinor
HarmonicMinor
Constructor & Destructor Documentation
KeySignature() [1/5]
constexpr lemons::music::scales::KeySignature::KeySignature () constexpr noexcept
Creates a key signature object representing C major.
KeySignature() [2/5]
constexpr lemons::music::scales::KeySignature::KeySignature (int numSharpsOrFlats, bool isSharps, Type typeToUse) explicit constexpr noexcept
KeySignature() [3/5]
constexpr lemons::music::scales::KeySignature::KeySignature (Type typeToUse, bool isSharps, int pitchClassOfRoot) explicit constexpr noexcept
References lemons::music::makeValidPitchClass().
KeySignature() [4/5]
constexpr lemons::music::scales::KeySignature::KeySignature (Type typeToUse, int pitchClassOfRoot) explicit constexpr noexcept
KeySignature() [5/5]
constexpr lemons::music::scales::KeySignature::KeySignature (const KeySignature & other) constexpr noexcept
Member Function Documentation
containsPitch() [1/2]
bool lemons::music::scales::Scale::containsPitch (const Pitch & pitch) const inherited
containsPitch() [2/2]
bool lemons::music::scales::Scale::containsPitch (int midiNoteNumber) const inherited
containsPitchClass()
bool lemons::music::scales::Scale::containsPitchClass (int pitchClass) const inherited
fromStringDescription()
static KeySignature lemons::music::scales::KeySignature::fromStringDescription (const String & description) static
getDominantKey()
KeySignature lemons::music::scales::KeySignature::getDominantKey () const noexcept
getEnharmonicKey()
KeySignature lemons::music::scales::KeySignature::getEnharmonicKey () const noexcept
getIntervals()
juce::Array< Interval > lemons::music::scales::Scale::getIntervals () const inherited
getIntervalsAsSemitones()
juce::Array< int > lemons::music::scales::KeySignature::getIntervalsAsSemitones () const final virtual
Implements lemons::music::scales::Scale.
getNumFlats()
constexpr int lemons::music::scales::KeySignature::getNumFlats () const constexpr noexcept
getNumSharps()
constexpr int lemons::music::scales::KeySignature::getNumSharps () const constexpr noexcept
getParallelKey()
KeySignature lemons::music::scales::KeySignature::getParallelKey () const noexcept
getPitchClasses()
juce::Array< int > lemons::music::scales::Scale::getPitchClasses () const inherited
getPitchClassOfRoot()
int lemons::music::scales::KeySignature::getPitchClassOfRoot () const final virtual noexcept
Implements lemons::music::scales::Scale.
getPitchClassOfScaleDegree()
int lemons::music::scales::Scale::getPitchClassOfScaleDegree (int scaleDegree) const noexcept inherited
getPitches() [1/2]
juce::Array< Pitch > lemons::music::scales::Scale::getPitches (int lowestMidiNote, int highestMidiNote) const inherited
getPitches() [2/2]
juce::Array< Pitch > lemons::music::scales::Scale::getPitches (int octaveNumber) const inherited
getRelativeKey()
KeySignature lemons::music::scales::KeySignature::getRelativeKey () const noexcept
getRoot()
Pitch lemons::music::scales::Scale::getRoot (int octaveNumber) const noexcept inherited
getRootAsString()
String lemons::music::scales::KeySignature::getRootAsString () const final virtual noexcept
Reimplemented from lemons::music::scales::Scale.
getScaleDegreeAsString()
String lemons::music::scales::KeySignature::getScaleDegreeAsString (int scaleDegree) const final virtual noexcept
Reimplemented from lemons::music::scales::Scale.
getStringDescription()
String lemons::music::scales::KeySignature::getStringDescription () const final virtual
Implements lemons::music::scales::Scale.
hasEnharmonicKey()
bool lemons::music::scales::KeySignature::hasEnharmonicKey () const noexcept
isDominantKeyOf()
bool lemons::music::scales::KeySignature::isDominantKeyOf (const KeySignature & other) const noexcept
isEnharmonicKeyOf()
bool lemons::music::scales::KeySignature::isEnharmonicKeyOf (const KeySignature & other) const noexcept
isFlatKey()
constexpr bool lemons::music::scales::KeySignature::isFlatKey () const constexpr noexcept
isMajorKey()
constexpr bool lemons::music::scales::KeySignature::isMajorKey () const constexpr noexcept
References Major.
Referenced by isMinorKey().
isMinorKey()
constexpr bool lemons::music::scales::KeySignature::isMinorKey () const constexpr noexcept
References isMajorKey().
isParallelKeyOf()
bool lemons::music::scales::KeySignature::isParallelKeyOf (const KeySignature & other) const noexcept
isRelativeKeyOf()
constexpr bool lemons::music::scales::KeySignature::isRelativeKeyOf (const KeySignature & other) const constexpr noexcept
isSharpKey()
constexpr bool lemons::music::scales::KeySignature::isSharpKey () const constexpr noexcept
notesPerOctave()
int lemons::music::scales::KeySignature::notesPerOctave () const final virtual noexcept
Implements lemons::music::scales::Scale.
operator!=() [1/2]
constexpr bool lemons::music::scales::KeySignature::operator!= (const KeySignature & other) const constexpr noexcept
operator!=() [2/2]
bool lemons::music::scales::Scale::operator!= (const Scale & other) const inherited
operator==() [1/2]
constexpr bool lemons::music::scales::KeySignature::operator== (const KeySignature & other) const constexpr noexcept
operator==() [2/2]
bool lemons::music::scales::Scale::operator== (const Scale & other) const inherited
The documentation for this class was generated from the following files:
KeySignature.h
KeySignature_impl.h