Lemons: lemons::dsp::BuiltEngineChain< SampleType, EngineTypes > Class Template Reference
lemons::dsp::BuiltEngineChain< SampleType, EngineTypes > Class Template Reference final
Public Types
using ValueType = SampleType
The engine's sample type is publicly accessible via this typedef.
Public Member Functions
BuiltEngineChain ()
void changeLatency (int newInternalBlocksize, bool setTopLevelEngineBlocksize=false)
Sets the latency in samples of the engine.
int getBlocksize () const noexcept
Returns the maximum blocksize this engine has been prepared to process.
int getNumChannels () const noexcept
Returns the number of channels this engine has been prepared to process.
double getSamplerate () const noexcept
Returns the engine's samplerate.
bool isInitialized () const noexcept
Returns true if prepare() has been called at least once since the object's construction or the last releaseResources() call.
void prepare (double samplerate, int blocksize, int numChannels=2)
Prepares the engine.
void releaseResources ()
Releases all of the engine's internal resources.
bool removeNode (int index)
Removes and deletes a node object at the specified index from the chain.
bool removeNode (Node &node)
Removes and deletes a node object from the chain.
int reportLatency () const noexcept final
Returns the latency in samples of the engine.
void reset ()
Call this method to reset the engine, without deallocating resources – for example, stopping all voices of a synth.
bool swapNodes (Node &node1, Node &node2)
Swaps the indices of two nodes in the chain.
bool swapNodesAtIndices (int index1, int index2)
Swaps the indices of the two nodes in the chain at the given indices.
Accessing nodes
Node * getNode (int index)
Returns the node at the specified index.
const Node * getNode (int index) const
Returns the node at the specified index.
template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node * getNodeOfType ()
Returns a pointer to the first node found that holds an Engine of the specified type.
template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
EngineType * getEngineOfType ()
Similar to getNodeOfType(), but returns a pointer to the actual engine object as its derived type, instead of a pointer to its containing node.
Adding nodes
Node & addNode (Node &newNode)
Adds a node to the end of the chain.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNode (Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeToFront (Node &newNode)
Adds a node to the front of the chain, at index 0.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeToFront (Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeAfter (Node &newNode, const Node &nodeToInsertAfter)
Adds a node after the specified other node.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeAfter (const Node &nodeToInsertAfter, Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeBefore (Node &newNode, const Node &nodeToInsertBefore)
Adds a node before the specified other node.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeBefore (const Node &nodeToInsertBefore, Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Accessing nodes
Node * getNode (int index)
Returns the node at the specified index.
const Node * getNode (int index) const
Returns the node at the specified index.
template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node * getNodeOfType ()
Returns a pointer to the first node found that holds an Engine of the specified type.
template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
EngineType * getEngineOfType ()
Similar to getNodeOfType(), but returns a pointer to the actual engine object as its derived type, instead of a pointer to its containing node.
Adding nodes
Node & addNode (Node &newNode)
Adds a node to the end of the chain.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNode (Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeToFront (Node &newNode)
Adds a node to the front of the chain, at index 0.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeToFront (Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeAfter (Node &newNode, const Node &nodeToInsertAfter)
Adds a node after the specified other node.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeAfter (const Node &nodeToInsertAfter, Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Node & addNodeBefore (Node &newNode, const Node &nodeToInsertBefore)
Adds a node before the specified other node.
template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) >
Node & createAndAddNodeBefore (const Node &nodeToInsertBefore, Args &&... args)
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Detailed Description
template<typename SampleType, template< typename T > typename... EngineTypes>
class lemons::dsp::BuiltEngineChain< SampleType, EngineTypes >
An EngineChain that you can pass templated Engine types to and it will instantiate them all and add them as nodes to the chain for you. For example:
template<typename SampleType>
struct MyFirstEngine : pubic Engine<SampleType>
{
};
template<typename SampleType>
struct MySecondEngine : pubic Engine<SampleType>
{
};
using MyChain = BuiltEngineChain<float, MyFirstEngine, MySecondEngine>;
Template Parameters
SampleType The floating-point type that will be used for all the nodes.
EngineTypes A list of unspecialized templated types. Each one of these types must inherit from Engine<SampleType> and must be default constructable.
See also
Engine, EngineChain
Member Typedef Documentation
ValueType
template<typename SampleType > using lemons::dsp::Engine< SampleType >::ValueType = SampleType inherited
The engine's sample type is publicly accessible via this typedef.
Constructor & Destructor Documentation
BuiltEngineChain()
template<typename SampleType , template< typename T > typename... EngineTypes> lemons::dsp::BuiltEngineChain< SampleType, EngineTypes >::BuiltEngineChain ()
Member Function Documentation
addNode()
template<typename SampleType > Node& lemons::dsp::EngineChain< SampleType >::addNode (Node & newNode) inherited
Adds a node to the end of the chain.
Returns
Reference to the node.
Referenced by lemons::dsp::EngineChain< SampleType >::createAndAddNode().
addNodeAfter()
template<typename SampleType > Node& lemons::dsp::EngineChain< SampleType >::addNodeAfter (Node & newNode, const Node & nodeToInsertAfter) inherited
Adds a node after the specified other node.
Note that this may change the indices of any other nodes already in the chain!
Returns
Reference to the node.
Referenced by lemons::dsp::EngineChain< SampleType >::createAndAddNodeAfter().
addNodeBefore()
template<typename SampleType > Node& lemons::dsp::EngineChain< SampleType >::addNodeBefore (Node & newNode, const Node & nodeToInsertBefore) inherited
Adds a node before the specified other node.
Note that this may change the indices of any other nodes already in the chain!
Returns
Reference to the node.
Referenced by lemons::dsp::EngineChain< SampleType >::createAndAddNodeBefore().
addNodeToFront()
template<typename SampleType > Node& lemons::dsp::EngineChain< SampleType >::addNodeToFront (Node & newNode) inherited
Adds a node to the front of the chain, at index 0.
Note that this may change the indices of any other nodes already in the chain!
Returns
Reference to the node.
Referenced by lemons::dsp::EngineChain< SampleType >::createAndAddNodeToFront().
changeLatency()
template<typename SampleType > void lemons::dsp::LatencyEngine< SampleType >::changeLatency (int newInternalBlocksize, bool setTopLevelEngineBlocksize = false) inherited
Sets the latency in samples of the engine.
Note that you must call Engine::prepare() at least once before calling this function, and the latency you specify here may be different than the blocksize you prepare the Engine base class with.
Parameters
newInternalBlocksize The new latency (and internal blocksize) of the engine, in samples.
setTopLevelEngineBlocksize When true, this calls Engine::prepare() and sets the Engine base class's blocksize to be the new latency. This may be undesirable, because this will not allow you to call the top level process() function with blocksizes larger than the latency you've declared here.
createAndAddNode()
template<typename SampleType > template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > Node& lemons::dsp::EngineChain< SampleType >::createAndAddNode (Args &&... args) inherited
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Adds the node to the end of the chain.
Template Parameters
EngineType The type of Engine object that the new node will hold. This type must inherit from Engine<SampleType>.
Returns
Reference to the node.
References lemons::dsp::EngineChain< SampleType >::addNode().
createAndAddNodeAfter()
template<typename SampleType > template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > Node& lemons::dsp::EngineChain< SampleType >::createAndAddNodeAfter (const Node & nodeToInsertAfter, Args &&... args) inherited
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Adds the node to the chain after the specified other node. Note that this may change the indices of any other nodes already in the chain!
Template Parameters
EngineType The type of Engine object that the new node will hold. This type must inherit from Engine<SampleType>.
Returns
Reference to the node.
References lemons::dsp::EngineChain< SampleType >::addNodeAfter().
createAndAddNodeBefore()
template<typename SampleType > template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > Node& lemons::dsp::EngineChain< SampleType >::createAndAddNodeBefore (const Node & nodeToInsertBefore, Args &&... args) inherited
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Adds the node to the chain before the specified other node. Note that this may change the indices of any other nodes already in the chain!
Template Parameters
EngineType The type of Engine object that the new node will hold. This type must inherit from Engine<SampleType>.
Returns
Reference to the node.
References lemons::dsp::EngineChain< SampleType >::addNodeBefore().
createAndAddNodeToFront()
template<typename SampleType > template<typename EngineType , typename... Args, LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > Node& lemons::dsp::EngineChain< SampleType >::createAndAddNodeToFront (Args &&... args) inherited
Creates a node holding an engine of the specified type, and forwards all arguments to the engine's constructor.
Adds the node to the front of the chain, at index 0. Note that this may change the indices of any other nodes already in the chain!
Template Parameters
EngineType The type of Engine object that the new node will hold. This type must inherit from Engine<SampleType>.
Returns
Reference to the node.
References lemons::dsp::EngineChain< SampleType >::addNodeToFront().
getBlocksize()
template<typename SampleType > int lemons::dsp::Engine< SampleType >::getBlocksize () const noexcept inherited
Returns the maximum blocksize this engine has been prepared to process.
This will return 0 if the engine is unprepared.
getEngineOfType()
template<typename SampleType > template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > EngineType* lemons::dsp::EngineChain< SampleType >::getEngineOfType () inherited
Similar to getNodeOfType(), but returns a pointer to the actual engine object as its derived type, instead of a pointer to its containing node.
Template Parameters
EngineType The type of Engine object to search for. This type must inherit from Engine<SampleType>.
See also
getNodeOfType()
getNode() [1/2]
template<typename SampleType > Node* lemons::dsp::EngineChain< SampleType >::getNode (int index) inherited
Returns the node at the specified index.
getNode() [2/2]
template<typename SampleType > const Node* lemons::dsp::EngineChain< SampleType >::getNode (int index) const inherited
Returns the node at the specified index.
getNodeOfType()
template<typename SampleType > template<typename EngineType , LEMONS_MUST_INHERIT_FROM(EngineType, Engine< SampleType >) > Node* lemons::dsp::EngineChain< SampleType >::getNodeOfType () inherited
Returns a pointer to the first node found that holds an Engine of the specified type.
Template Parameters
EngineType The type of Engine object to search for. This type must inherit from Engine<SampleType>.
See also
getEngineOfType()
getNumChannels()
template<typename SampleType > int lemons::dsp::Engine< SampleType >::getNumChannels () const noexcept inherited
Returns the number of channels this engine has been prepared to process.
This will return 0 if the engine is unprepared.
getSamplerate()
template<typename SampleType > double lemons::dsp::Engine< SampleType >::getSamplerate () const noexcept inherited
Returns the engine's samplerate.
This will return 0. if the engine is unprepared.
Referenced by lemons::dsp::osc::Engine< float, lemons::dsp::osc::Triangle >::setFrequency().
isInitialized()
template<typename SampleType > bool lemons::dsp::Engine< SampleType >::isInitialized () const noexcept inherited
Returns true if prepare() has been called at least once since the object's construction or the last releaseResources() call.
See also
prepare(), releaseResources()
prepare()
template<typename SampleType > void lemons::dsp::Engine< SampleType >::prepare (double samplerate, int blocksize, int numChannels = 2) inherited
Prepares the engine.
process() [1/4]
template<typename SampleType > void lemons::dsp::Engine< SampleType >::process (AudioBuffer< SampleType > & inplaceInAndOut, bool isBypassed = false) inherited
Processes the audio engine with in-place audio I/O and no MIDI.
The internal renderBlock() function will be called with an empty dummy MidiBuffer.
Parameters
inplaceInAndOut The audio buffer that the input will be read from and the output will be written to.
isBypassed Should be true if the engine is bypassed this frame.
process() [2/4]
template<typename SampleType > void lemons::dsp::Engine< SampleType >::process (AudioBuffer< SampleType > & inplaceInAndOut, MidiBuffer & midiMessages, bool isBypassed = false) inherited
Processes the audio engine with in-place audio I/O and MIDI.
Parameters
inplaceInAndOut The audio buffer that the input will be read from and the output will be written to.
midiMessages MIDI I/O buffer. The engine's MIDI output will be returned in-place.
isBypassed Should be true if the engine is bypassed this frame.
process() [3/4]
template<typename SampleType > void lemons::dsp::Engine< SampleType >::process (const AudioBuffer< SampleType > & input, AudioBuffer< SampleType > & output, bool isBypassed = false) inherited
Processes the audio engine with separate audio in and out and no MIDI.
The internal renderBlock() function will be called with an empty dummy MidiBuffer.
Parameters
input The audio input.
output The audio output.
isBypassed Should be true if the engine is bypassed this frame.
process() [4/4]
template<typename SampleType > void lemons::dsp::Engine< SampleType >::process (const AudioBuffer< SampleType > & input, AudioBuffer< SampleType > & output, MidiBuffer & midiMessages, bool isBypassed = false) inherited
Processes the audio engine with separate audio in and out, and MIDI.
Parameters
input The audio input.
output The audio output.
midiMessages MIDI I/O buffer. The engine's MIDI output will be returned in-place.
isBypassed Should be true if the engine is bypassed this frame.
releaseResources()
template<typename SampleType > void lemons::dsp::Engine< SampleType >::releaseResources () inherited
Releases all of the engine's internal resources.
removeNode() [1/2]
template<typename SampleType > bool lemons::dsp::EngineChain< SampleType >::removeNode (int index) inherited
Removes and deletes a node object at the specified index from the chain.
Returns
True if the operation succeeds.
removeNode() [2/2]
template<typename SampleType > bool lemons::dsp::EngineChain< SampleType >::removeNode (Node & node) inherited
Removes and deletes a node object from the chain.
Returns
True if the operation succeeds. This will really only fail if you pass a pointer to a Node object that is not in this chain.
reportLatency()
template<typename SampleType > int lemons::dsp::LatencyEngine< SampleType >::reportLatency () const final virtual noexcept inherited
Returns the latency in samples of the engine.
Reimplemented from lemons::dsp::Engine< SampleType >.
reset()
template<typename SampleType > void lemons::dsp::Engine< SampleType >::reset () inherited
Call this method to reset the engine, without deallocating resources – for example, stopping all voices of a synth.
swapNodes()
template<typename SampleType > bool lemons::dsp::EngineChain< SampleType >::swapNodes (Node & node1, Node & node2) inherited
Swaps the indices of two nodes in the chain.
Returns
True if the operation was successful
swapNodesAtIndices()
template<typename SampleType > bool lemons::dsp::EngineChain< SampleType >::swapNodesAtIndices (int index1, int index2) inherited
Swaps the indices of the two nodes in the chain at the given indices.
Returns
True if the operation was successful
The documentation for this class was generated from the following file:
EngineChain.h