Lemons: lemons::music::CompoundInterval Class Reference
lemons::music::CompoundInterval Class Reference final
A class for representing intervals larger than an octave.
Public Member Functions
constexpr CompoundInterval (const CompoundInterval &other) noexcept
Copy constructor.
constexpr CompoundInterval (int kind, Interval::Quality quality) noexcept
Creates a compound interval from a given kind and quality, eg, major ninth, etc.
constexpr CompoundInterval (int numSemitones) noexcept
Constructs a compound interval with the given number of semitones.
constexpr CompoundInterval (int octaves, const Interval &simpleInterval) noexcept
Creates a compound interval with the given number of octaves and the given simple interval component.
Pitch applyToPitch (const Pitch &other, bool above) const noexcept
Returns a new pitch object that represents the note this interval's distance above or below the passed pitch object.
constexpr int getCents_EqualTemperament () const noexcept
Returns the number of cents this interval represents in equal temperament.
juce::Array< double > getCents_JustIntonation () const
Returns an array of possible cents values this interval can represent in just intonation, taking enharmonic spelling into account.
constexpr int getKind () const noexcept
Returns the kind of this compound interval as an integer, eg, 9, 10, etc.
constexpr int getNumOctaves () const noexcept
Returns the number of octaves contained in this compound interval.
constexpr int getNumSemitones () const noexcept
Returns the number of semitones this compound interval represents.
constexpr Interval::Quality getQuality () const noexcept
Returns the quality of this compound interval.
constexpr Interval getSimpleInterval () const noexcept
Returns the simple interval component of this compound interval.
String getStringDescription (bool useShort=false) const
Returns a string description of this compound interval.
constexpr bool hasSameSimpleInterval (const CompoundInterval &other) const noexcept
Returns true if the two compound intervals have the same sub-octave component, regardless of how many octaves either compound interval spans.
constexpr bool isEnharmonicTo (const CompoundInterval &other) const noexcept
Returns true if the two intervals represent the same number of semitones, regardless of their enharmonic spelling.
constexpr bool operator!= (const CompoundInterval &other) const noexcept
Returns true if the two intervals are not exactly equal.
constexpr bool operator< (const CompoundInterval &other) const noexcept
Returns true if this interval is semantically smaller than the other one, taking enharmonic spellings into account.
constexpr CompoundInterval & operator= (const CompoundInterval &other) noexcept
Assignment operator.
constexpr bool operator== (const CompoundInterval &other) const noexcept
Returns true if the two compound intervals are exactly equal; that is, have the same number of octaves, and their simple interval components are exactly equal in kind and quality.
constexpr bool operator> (const CompoundInterval &other) const noexcept
Returns true if this interval is semantically larger than the other one, taking enharmonic spellings into account.
Static Public Member Functions
static CompoundInterval fromPitches (const Pitch &pitch1, const Pitch &pitch2) noexcept
Returns a compound interval object representing the distance between two pitch objects.
static constexpr CompoundInterval fromPitches (int midiPitch1, int midiPitch2) noexcept
Returns a compound interval object representing the distance between two MIDI notes.
Detailed Description
A class for representing intervals larger than an octave.
Internally, the interval is represented as a number of octaves and an Interval object. This class is capable of representing intervals smaller than an octave, but if you know your interval is going to be smaller than an octave, prefer to use the Interval class directly.
Constructor & Destructor Documentation
CompoundInterval() [1/4]
constexpr lemons::music::CompoundInterval::CompoundInterval (int octaves, const Interval & simpleInterval) explicit constexpr noexcept
Creates a compound interval with the given number of octaves and the given simple interval component.
If the simple interval is a perfect or augmented octave, the number of octaves will be incremented and the simple interval component will be reduced to a perfect or augmented unison.
References lemons::music::Interval::Diminished.
CompoundInterval() [2/4]
constexpr lemons::music::CompoundInterval::CompoundInterval (int kind, Interval::Quality quality) explicit constexpr noexcept
Creates a compound interval from a given kind and quality, eg, major ninth, etc.
CompoundInterval() [3/4]
constexpr lemons::music::CompoundInterval::CompoundInterval (int numSemitones) explicit constexpr noexcept
Constructs a compound interval with the given number of semitones.
References lemons::music::Interval::fromNumSemitones().
CompoundInterval() [4/4]
constexpr lemons::music::CompoundInterval::CompoundInterval (const CompoundInterval & other) constexpr noexcept
Copy constructor.
Member Function Documentation
applyToPitch()
Pitch lemons::music::CompoundInterval::applyToPitch (const Pitch & other, bool above) const noexcept
Returns a new pitch object that represents the note this interval's distance above or below the passed pitch object.
Parameters
other The pitch object to start from.
above When true, the returned pitch will be this interval's distance above the passed pitch. When false, the returned pitch will be this interval's distance below the passed pitch.
fromPitches() [1/2]
static CompoundInterval lemons::music::CompoundInterval::fromPitches (const Pitch & pitch1, const Pitch & pitch2) static noexcept
Returns a compound interval object representing the distance between two pitch objects.
fromPitches() [2/2]
constexpr CompoundInterval lemons::music::CompoundInterval::fromPitches (int midiPitch1, int midiPitch2) static constexpr noexcept
Returns a compound interval object representing the distance between two MIDI notes.
References lemons::math::abs().
getCents_EqualTemperament()
constexpr int lemons::music::CompoundInterval::getCents_EqualTemperament () const constexpr noexcept
Returns the number of cents this interval represents in equal temperament.
References getNumSemitones().
getCents_JustIntonation()
juce::Array< double > lemons::music::CompoundInterval::getCents_JustIntonation () const
Returns an array of possible cents values this interval can represent in just intonation, taking enharmonic spelling into account.
getKind()
constexpr int lemons::music::CompoundInterval::getKind () const constexpr noexcept
Returns the kind of this compound interval as an integer, eg, 9, 10, etc.
References lemons::music::Interval::getKind().
getNumOctaves()
constexpr int lemons::music::CompoundInterval::getNumOctaves () const constexpr noexcept
Returns the number of octaves contained in this compound interval.
getNumSemitones()
constexpr int lemons::music::CompoundInterval::getNumSemitones () const constexpr noexcept
Returns the number of semitones this compound interval represents.
References lemons::music::Interval::getNumSemitones().
Referenced by getCents_EqualTemperament().
getQuality()
constexpr Interval::Quality lemons::music::CompoundInterval::getQuality () const constexpr noexcept
Returns the quality of this compound interval.
The quality of compound intervals is determined by the quality of their simple interval component; this is identical to calling:
compoundInterval.getSimpleInterval().getQuality();
References lemons::music::Interval::getQuality().
getSimpleInterval()
constexpr Interval lemons::music::CompoundInterval::getSimpleInterval () const constexpr noexcept
Returns the simple interval component of this compound interval.
The interval object returned by this function will always be a diminished octave or smaller, and may be a perfect unison.
getStringDescription()
String lemons::music::CompoundInterval::getStringDescription (bool useShort = false) const
Returns a string description of this compound interval.
Parameters
useShort When true, a shorthand version of the description will be returned – for example, "M9" instead of "Major ninth", etc.
hasSameSimpleInterval()
constexpr bool lemons::music::CompoundInterval::hasSameSimpleInterval (const CompoundInterval & other) const constexpr noexcept
Returns true if the two compound intervals have the same sub-octave component, regardless of how many octaves either compound interval spans.
For example, a major tenth and a major seventeenth would return true, because they are both compound major thirds.
isEnharmonicTo()
constexpr bool lemons::music::CompoundInterval::isEnharmonicTo (const CompoundInterval & other) const constexpr noexcept
Returns true if the two intervals represent the same number of semitones, regardless of their enharmonic spelling.
operator!=()
constexpr bool lemons::music::CompoundInterval::operator!= (const CompoundInterval & other) const constexpr noexcept
Returns true if the two intervals are not exactly equal.
operator<()
constexpr bool lemons::music::CompoundInterval::operator< (const CompoundInterval & other) const constexpr noexcept
Returns true if this interval is semantically smaller than the other one, taking enharmonic spellings into account.
operator=()
constexpr CompoundInterval & lemons::music::CompoundInterval::operator= (const CompoundInterval & other) constexpr noexcept
Assignment operator.
operator==()
constexpr bool lemons::music::CompoundInterval::operator== (const CompoundInterval & other) const constexpr noexcept
Returns true if the two compound intervals are exactly equal; that is, have the same number of octaves, and their simple interval components are exactly equal in kind and quality.
operator>()
constexpr bool lemons::music::CompoundInterval::operator> (const CompoundInterval & other) const constexpr noexcept
Returns true if this interval is semantically larger than the other one, taking enharmonic spellings into account.
The documentation for this class was generated from the following files:
CompoundInterval.h
CompoundInterval_impl.h