Lemons: lemons::plugin::ParameterList Class Reference
lemons::plugin::ParameterList Class Reference
Plugins » lemons_plugin_parameters » parameters
This class manages a list of a plugin's parameters.
Classes
struct Listener
Class that fires a lambda callback each time any of its ParameterList's parameters change.
Public Member Functions
ParameterList (const String &name="Parameters", UndoManager *um=nullptr)
Creates a parameter list.
template<typename... Args>
void add (ParamHolderBase &first, Args &&... rest)
Adds a list of parameters to the list.
void add (ParamHolderBase &param)
Adds a single parameter to the list.
void addAllParametersAsInternal ()
Adds all the list's parameters to the ParameterList's dummy internal AudioProcessor.
template<typename... Args>
void addInternal (ParamHolderBase &first, Args &&... rest)
Adds a list of parameters to the list as "internal" parameters.
void addInternal (ParamHolderBase &param)
Adds a single parameter to the list as an "internal" parameter.
void addParametersTo (juce::AudioProcessor &processor)
Adds the list's managed parameters to a juce::AudioProcessor.
void deserialize (const ValueTree &tree)
Restores a previously saved state.
Parameter * getParameterWithName (const String name, bool internationalizeName=false)
Searches for a parameter in the list with a specified name.
void processMidi (const MidiBuffer &midiMessages)
Processes the next block of MIDI for your plugin.
void processMidiMessage (const MidiMessage &message)
Processes a single incoming MIDI message.
void refreshAllDefaults ()
Calls Parameter::refreshDefault() on all the list's parameters.
void resetAllToDefault ()
Calls Parameter::resetToDefault() on all the list's parameters.
ValueTree serialize ()
Serializes the state of this object and returns a ValueTree.
void setLastMovedMidiControllerNumberParameter (IntParam &param)
Sets a parameter to use to report the last moved MIDI CC number.
void setLastMovedMidiControllerValueParameter (IntParam &param)
Sets a parameter to use to report the last moved MIDI CC value.
void setPitchbendParameter (IntParam &param)
Sets a parameter to use to report the pitch wheel's current value.
void setUndoManager (UndoManager &um)
Sets the UndoManager to be used by all the list's parameters.
Detailed Description
This class manages a list of a plugin's parameters.
This class allows you to mark some parameters as "internal", not to be shown in the DAW's list of automatable parameters. Parameters marked "internal" (ie, not automatable), will be added to a dummy internal audio processor inside the ParameterList. The benefit of this is that these internal parameters will not show up in your DAW's list of parameters for your plugin under any circumstances, but they will still function as if they were added in the normal manner.
This class also allows you to easily serialize all of your parameters using my SerializableData API.
I usually recommend creating a subclass of ParameterList for your product. For example:
using namespace lemons;
struct MyParameters : plugin::ParameterList
{
    MyParameters() : ParameterList ("MyParameters")
    {
        add (reverbToggle, delayToggle);
        // maybe this is just for communication with the GUI?
        addInternal (feedbackLevel);
    }
    ToggleParam reverbToggle {"Reverb toggle", true};
    ToggleParam delayToggle {"Delay toggle", false};
    dbParam feedbackLevel {"Feedback", -6.f};
};
Then, in your processor, you can simply do:
struct MyProcessor : juce::AudioProcessor
{
    MyProcessor()
    {
        params.addParametersTo (*this);
    }
    MyParameters params;
};
You should usually only need one ParameterList for your plugin.
See also
Parameter, ParameterHolder
Constructor & Destructor Documentation
ParameterList()
lemons::plugin::ParameterList::ParameterList (const String & name = "Parameters", UndoManager * um = nullptr)
Creates a parameter list.
Parameters
name The identifier used for the list of parameters as a whole in serialization.
um Optional pointer to an UndoManager to use with all of your parameters. This can also be set after construction with setUndoManager().
Member Function Documentation
add() [1/2]
template<typename... Args> void lemons::plugin::ParameterList::add (ParamHolderBase & first, Args &&... rest)
Adds a list of parameters to the list.
You can call this function with any number of ParameterHolder objects with any parameter types.
References add().
add() [2/2]
void lemons::plugin::ParameterList::add (ParamHolderBase & param)
Adds a single parameter to the list.
The parameter must live inside a ParameterHolder object, and will be added as a normal (ie, NOT "internal") parameter.
Referenced by add().
addAllParametersAsInternal()
void lemons::plugin::ParameterList::addAllParametersAsInternal ()
Adds all the list's parameters to the ParameterList's dummy internal AudioProcessor.
This is useful for situations where you may want to instantiate the state of your plugin without creating the rest of your processor – perhaps, in a GUI-only app version, or something like that. Simply call this function in the constructor of your app's main component and your plugin's state will be ready to use normally, as if it's living inside your processor.
addInternal() [1/2]
template<typename... Args> void lemons::plugin::ParameterList::addInternal (ParamHolderBase & first, Args &&... rest)
Adds a list of parameters to the list as "internal" parameters.
You can call this function with any number of ParameterHolder objects with any parameter types.
References addInternal().
addInternal() [2/2]
void lemons::plugin::ParameterList::addInternal (ParamHolderBase & param)
Adds a single parameter to the list as an "internal" parameter.
The parameter must live inside a ParameterHolder object.
Referenced by addInternal().
addParametersTo()
void lemons::plugin::ParameterList::addParametersTo (juce::AudioProcessor & processor)
Adds the list's managed parameters to a juce::AudioProcessor.
You should first add all your parameters to the list using add() or addInternal(), then call this to add all the parameters to your processor.
Internal parameters will be added to a dummy internal AudioProcessor inside the ParameterList, so that they will not show up in your AudioProcessor's parameter list under any circumstances.
deserialize()
void lemons::SerializableData::deserialize (const ValueTree & tree) inherited
Restores a previously saved state.
Internally, this will create a TreeLoader object and call the virtual serialize(TreeReflector&) function.
Parameters
tree The saved state you wish to restore. This should usually be a ValueTree you got from a previous call to serialize().
If the state is incomplete, for a different kind of object, or otherwise corrupted, this function will only change the properties that it can successfully parse from the passed state. For example, if your serializable object uses properties named "apple", "orange", and "grape", and you pass a ValueTree with entries for "apple", "grapefruit", and "mango", then the "grapefruit" and "mango" properties will be ignored, and only the "apple" property will actually be loaded.
See also
TreeLoader, TreeReflector
getParameterWithName()
Parameter* lemons::plugin::ParameterList::getParameterWithName (const String name, bool internationalizeName = false)
Searches for a parameter in the list with a specified name.
This may return nullptr if a parameter with the specified name can't be found.
processMidi()
void lemons::plugin::ParameterList::processMidi (const MidiBuffer & midiMessages)
Processes the next block of MIDI for your plugin.
You must call this every processBlock() in order for the pitchbend and MIDI CC reporting parameters to work properly.
This function processes all of the messages in the buffer at once; to get sample-accurate processing with smaller blocks rendered in between each MIDI message, use the ParameterProcessorBase class.
See also
ParameterProcessorBase
processMidiMessage()
void lemons::plugin::ParameterList::processMidiMessage (const MidiMessage & message)
Processes a single incoming MIDI message.
You must call this every processBlock() in order for the pitchbend and MIDI CC reporting parameters to work properly.
refreshAllDefaults()
void lemons::plugin::ParameterList::refreshAllDefaults ()
Calls Parameter::refreshDefault() on all the list's parameters.
This sets all the parameters' default values to be their current values.
This is useful, for example, after loading a preset: load the new state, then call this function, then any calls to Parameter::resetToDefault() will set the parameter to its value from the last loaded preset.
resetAllToDefault()
void lemons::plugin::ParameterList::resetAllToDefault ()
Calls Parameter::resetToDefault() on all the list's parameters.
This sets all the parameters back to their saved default values.
serialize()
ValueTree lemons::SerializableData::serialize () inherited
Serializes the state of this object and returns a ValueTree.
Internally, this will create a TreeSaver object and call the virtual serialize(TreeReflector&) function.
See also
TreeSaver, TreeReflector
setLastMovedMidiControllerNumberParameter()
void lemons::plugin::ParameterList::setLastMovedMidiControllerNumberParameter (IntParam & param)
Sets a parameter to use to report the last moved MIDI CC number.
Calling this is optional, and mainly provided for convenience.
After calling this, the IntParameter specified will always have the same value as the last changed MIDI controller number. Any listners of this parameter will recieve appropriate callbacks each time the MIDI CC number changes.
setLastMovedMidiControllerValueParameter()
void lemons::plugin::ParameterList::setLastMovedMidiControllerValueParameter (IntParam & param)
Sets a parameter to use to report the last moved MIDI CC value.
Calling this is optional, and mainly provided for convenience.
After calling this, the IntParameter specified will always have the same value as the last changed MIDI CC value. Any listners of this parameter will recieve appropriate callbacks each time the MIDI CC value changes.
setPitchbendParameter()
void lemons::plugin::ParameterList::setPitchbendParameter (IntParam & param)
Sets a parameter to use to report the pitch wheel's current value.
Calling this is optional, and mainly provided for convenience.
After calling this, the IntParameter specified will always have the same value as the MIDI pitchwheel data coming into your plugin, and any listeners of that parameter will recieve appropriate callbacks when the pitchwheel is moved.
setUndoManager()
void lemons::plugin::ParameterList::setUndoManager (UndoManager & um)
Sets the UndoManager to be used by all the list's parameters.
The documentation for this class was generated from the following file:
ParameterList.h