Lemons: lemons::plugin::Parameter Class Reference
lemons::plugin::Parameter Class Reference
Classes
struct LambdaListener
A listener class that fires lambdas for each callback.
struct Listener
A Listener class that will be notified when aspects of a Parameter change.
Public Member Functions
Parameter (const ParameterTraits &traits)
Creates a parameter from a ParameterTraits object.
Parameter (const String &paramName, const ParameterRange &paramRange, float paramDefaultValue=1.f, BasicValToStringFunc valueToTextFuncToUse=nullptr, BasicStringToValFunc textToValueFuncToUse=nullptr, const String &paramLabel={}, bool isAutomatable=true, bool metaParam=false, ParameterCategory parameterCategory=ParameterCategory::genericParameter)
Creates a parameter.
float getDenormalizedValue () const noexcept
Returns the parameter's current value, in the parameter's denormalized range.
const ParameterRange & getNormalisableRange () const final
Returns this parameter's range object.
float getNormalizedValue () const noexcept
Returns the parameter's current value, in a normalized 0-1 range.
bool isAutomatable () const final
Returns true if this parameter is automatable by the user's DAW.
bool isMetaParameter () const final
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
void setDenormalizedValue (float value)
Sets the parameter's value, in the parameter's denormalized range.
void setNormalizedValue (float value)
Sets the parameter's value, in a normalized 0-1 range.
Static Public Attributes
static constexpr auto id_prop = "id"
Protected Member Functions
float denormalize (float input) const noexcept
Denormalizes the passed value using the parameter's NormalisableRange object.
float normalize (float input) const noexcept
Normalizes the passed value using the parameter's NormalisableRange object.
Static Protected Attributes
static constexpr auto controller_prop = "controllerNumber"
static constexpr auto default_prop = "default"
static constexpr auto value_prop = "value"
static constexpr auto valueTreeType = "PARAM"
parameter_saving_and_loading Functions for state saving and loading
virtual ValueTree saveToValueTree () const
Saves the state of this parameter to a ValueTree.
virtual void loadFromValueTree (const ValueTree &tree)
Restores the parameter's state from a ValueTree.
virtual ParameterTraits getParameterTraits () const
Returns a ParameterTraits object representing this parameter.
Detailed Description
A plugin parameter class.
See also
TypedParameter, ParameterTraits
Constructor & Destructor Documentation
Parameter() [1/2]
lemons::plugin::Parameter::Parameter (const String & paramName, const ParameterRange & paramRange, float paramDefaultValue = 1.f, BasicValToStringFunc valueToTextFuncToUse = nullptr, BasicStringToValFunc textToValueFuncToUse = nullptr, const String & paramLabel = {}, bool isAutomatable = true, bool metaParam = false, ParameterCategory parameterCategory = ParameterCategory::genericParameter) explicit
Creates a parameter.
Parameters
paramName The name of this parameter.
paramRange The range of values that this parameter can have.
paramDefaultValue The default value of this parameter.
valueToTextFuncToUse An optional lambda function that converts this parameter's value to a text description.
textToValueFuncToUse An optional lambda function that converts a text input string to a value for this parameter.
paramLabel An optional label to use for this parameter's units.
isAutomatable Boolean flag that indicates whether this parameter should be automatable in the user's DAW.
metaParam Boolean flag that indicates whether this parameter represents a "meta-parameter" – that is, a parameter that controls other parameters.
parameterCategory An optional parameter category. See juce::AudioProcessorParameter::Category.
Parameter() [2/2]
lemons::plugin::Parameter::Parameter (const ParameterTraits & traits) explicit
Creates a parameter from a ParameterTraits object.
Member Function Documentation
beginGesture()
void lemons::plugin::Parameter::beginGesture ()
Begins a change gesture for this parameter.
denormalize()
float lemons::plugin::Parameter::denormalize (float input) const protected noexcept
Denormalizes the passed value using the parameter's NormalisableRange object.
Referenced by getDenormalizedDefault(), and getDenormalizedValue().
endGesture()
void lemons::plugin::Parameter::endGesture ()
Ends any active change gesture for this parameter.
getDenormalizedDefault()
float lemons::plugin::Parameter::getDenormalizedDefault () const noexcept
Returns the parameter's default value, in the parameter's denormalized range.
See also
getNormalizedDefault()
References denormalize(), and getNormalizedDefault().
getDenormalizedValue()
float lemons::plugin::Parameter::getDenormalizedValue () const noexcept
Returns the parameter's current value, in the parameter's denormalized range.
See also
getNormalizedValue()
References denormalize().
getMidiControllerNumber()
int lemons::plugin::Parameter::getMidiControllerNumber () const noexcept
Returns the number of the MIDI controller mapped to this parameter, or -1 if this parameter is unmapped.
getNormalisableRange()
const ParameterRange& lemons::plugin::Parameter::getNormalisableRange () const final
Returns this parameter's range object.
getNormalizedDefault()
float lemons::plugin::Parameter::getNormalizedDefault () const noexcept
Returns the parameter's default value, in a normalized 0-1 range.
See also
getDenormalizedDefault()
Referenced by getDenormalizedDefault(), refreshDefault(), and resetToDefault().
getNormalizedValue()
float lemons::plugin::Parameter::getNormalizedValue () const noexcept
Returns the parameter's current value, in a normalized 0-1 range.
See also
getDenormalizedValue()
getParameterTraits()
virtual ParameterTraits lemons::plugin::Parameter::getParameterTraits () const virtual
Returns a ParameterTraits object representing this parameter.
An object identical to this one can be recreated using the constructor that takes a ParameterTraits object.
Reimplemented in lemons::plugin::TypedParameter< ValueType >.
getTextForCurrentValue()
String lemons::plugin::Parameter::getTextForCurrentValue () const
Returns a textual representation of the parameter's current value.
getTextForDenormalizedValue()
String lemons::plugin::Parameter::getTextForDenormalizedValue (float value) const
Returns a textual description of a value in the parameter's denormalized range.
See also
getTextForNormalizedValue()
References getTextForNormalizedValue(), and normalize().
Referenced by getTextForMax(), and getTextForMin().
getTextForMax()
String lemons::plugin::Parameter::getTextForMax () const
Returns a textual description of the parameter's maximum value.
See also
getTextForMin()
References getTextForDenormalizedValue().
getTextForMin()
String lemons::plugin::Parameter::getTextForMin () const
Returns a textual description of the parameter's minimum value.
See also
getTextForMax()
References getTextForDenormalizedValue().
getTextForNormalizedValue()
String lemons::plugin::Parameter::getTextForNormalizedValue (float value) const
Returns a textual description of a normalized value in the range 0-1.
See also
getTextForDenormalizedValue()
Referenced by getTextForDenormalizedValue().
isAutomatable()
bool lemons::plugin::Parameter::isAutomatable () const final
Returns true if this parameter is automatable by the user's DAW.
isChanging()
bool lemons::plugin::Parameter::isChanging () const noexcept
Returns true if this parameter is currently in the middle of a change gesture.
isMetaParameter()
bool lemons::plugin::Parameter::isMetaParameter () const final
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
isMidiControllerMapped()
bool lemons::plugin::Parameter::isMidiControllerMapped () const noexcept
Returns true if this parameter is currently mapped to a MIDI controller.
loadFromValueTree()
virtual void lemons::plugin::Parameter::loadFromValueTree (const ValueTree & tree) virtual
Restores the parameter's state from a ValueTree.
Reimplemented in lemons::plugin::MetaParameter< ValueType >, lemons::plugin::MetaParameter< float >, lemons::plugin::TypedParameter< ValueType >, lemons::plugin::TypedParameter< float >, lemons::plugin::TypedParameter< bool >, lemons::plugin::MeterParameter< ValueType >, lemons::plugin::MeterParameter< float >, and lemons::plugin::LFO.
normalize()
float lemons::plugin::Parameter::normalize (float input) const protected noexcept
Normalizes the passed value using the parameter's NormalisableRange object.
Referenced by getTextForDenormalizedValue(), setDenormalizedDefault(), and setDenormalizedValue().
processNewControllerMessage()
bool lemons::plugin::Parameter::processNewControllerMessage (int controllerNumber, int controllerValue)
Call this function with each MIDI CC message your plugin recieves, and the Parameter class will automatically update itself with changes in the appropriate controller, if a mapping is active.
Returns
True if this parameter is mapped to the passed controller number.
refreshDefault()
void lemons::plugin::Parameter::refreshDefault ()
Sets the parameter's current value as the default value.
References getNormalizedDefault(), and setNormalizedDefault().
removeMidiControllerMapping()
void lemons::plugin::Parameter::removeMidiControllerMapping () noexcept
Removes the MIDI controller mapping, if any.
References setMidiControllerNumber().
resetToDefault()
void lemons::plugin::Parameter::resetToDefault ()
Resets the parameter to the saved default value.
References getNormalizedDefault(), and setNormalizedValue().
saveToValueTree()
virtual ValueTree lemons::plugin::Parameter::saveToValueTree () const virtual
Saves the state of this parameter to a ValueTree.
Reimplemented in lemons::plugin::MetaParameter< ValueType >, lemons::plugin::TypedParameter< ValueType >, lemons::plugin::MeterParameter< ValueType >, and lemons::plugin::LFO.
setDenormalizedDefault()
void lemons::plugin::Parameter::setDenormalizedDefault (float value)
Sets the parameter's default, in the parameter's denormalized range.
See also
setNormalizedDefault()
References normalize(), and setNormalizedDefault().
setDenormalizedValue()
void lemons::plugin::Parameter::setDenormalizedValue (float value)
Sets the parameter's value, in the parameter's denormalized range.
See also
setNormalizedValue()
References normalize(), and setNormalizedValue().
setMidiControllerNumber()
void lemons::plugin::Parameter::setMidiControllerNumber (int newControllerNumber)
Maps this parameter to listen for changes in a specified MIDI controller number.
Referenced by removeMidiControllerMapping().
setNormalizedDefault()
void lemons::plugin::Parameter::setNormalizedDefault (float value)
Sets the parameter's default, in a normalized 0-1 range.
See also
setDenormalizedDefault()
Referenced by refreshDefault(), and setDenormalizedDefault().
setNormalizedValue()
void lemons::plugin::Parameter::setNormalizedValue (float value)
Sets the parameter's value, in a normalized 0-1 range.
See also
setDenormalizedValue()
Referenced by resetToDefault(), and setDenormalizedValue().
Member Data Documentation
controller_prop
constexpr auto lemons::plugin::Parameter::controller_prop = "controllerNumber" static protected
default_prop
constexpr auto lemons::plugin::Parameter::default_prop = "default" static protected
id_prop
constexpr auto lemons::plugin::Parameter::id_prop = "id" static constexpr
value_prop
constexpr auto lemons::plugin::Parameter::value_prop = "value" static protected
valueTreeType
constexpr auto lemons::plugin::Parameter::valueTreeType = "PARAM" static constexpr protected
The documentation for this class was generated from the following file:
Parameter.h