Lemons: lemons::plugin::State Class Reference
lemons::plugin::State Class Reference
Plugins » lemons_plugin » state
Base class for a plugin's entire state.
Classes
struct Listener
Public Member Functions
State ()
virtual ~State ()=default
template<typename... Args>
void add (Parameter &first, Args &&... rest)
void add (Parameter &parameter)
void addTo (juce::AudioProcessor &processor) const
Parameter * getNamedParameter (const String &name) const
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, Parameter) >
ParameterType * getTypedParameter (const String &name) const
bool isControllerMapped (int number) const
void loadFromValueTree (const ValueTree &tree)
void processControllerMessage (int number, int value)
void resetAllControllerMappedParams ()
ValueTree saveToValueTree (bool currentProgramOnly) const
Public Attributes
ToggleParameter bypass { "Bypass", false }
Dimensions editorSize { Dimensions::getDefault() }
ProgramManager programs
Private Member Functions
virtual void loadCustomStateData (const ValueTree &tree)
virtual ValueTree saveCustomStateData (const String &valueTreeType, bool currentProgramOnly) const
Detailed Description
Base class for a plugin's entire state.
Constructor & Destructor Documentation
State()
lemons::plugin::State::State ()
~State()
virtual lemons::plugin::State::~State () virtual default
Member Function Documentation
add() [1/2]
template<typename... Args> void lemons::plugin::State::add (Parameter & first, Args &&... rest)
References add().
add() [2/2]
void lemons::plugin::State::add (Parameter & parameter)
Referenced by add().
addTo()
void lemons::plugin::State::addTo (juce::AudioProcessor & processor) const
getNamedParameter()
Parameter* lemons::plugin::State::getNamedParameter (const String & name) const
Referenced by getTypedParameter().
getTypedParameter()
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, Parameter) > ParameterType* lemons::plugin::State::getTypedParameter (const String & name) const
References getNamedParameter().
isControllerMapped()
bool lemons::plugin::State::isControllerMapped (int number) const
loadCustomStateData()
virtual void lemons::plugin::State::loadCustomStateData (const ValueTree & tree) private virtual
loadFromValueTree()
void lemons::plugin::State::loadFromValueTree (const ValueTree & tree)
processControllerMessage()
void lemons::plugin::State::processControllerMessage (int number, int value)
resetAllControllerMappedParams()
void lemons::plugin::State::resetAllControllerMappedParams ()
saveCustomStateData()
virtual ValueTree lemons::plugin::State::saveCustomStateData (const String & valueTreeType, bool currentProgramOnly) const private virtual
saveToValueTree()
ValueTree lemons::plugin::State::saveToValueTree (bool currentProgramOnly) const
Member Data Documentation
bypass
ToggleParameter lemons::plugin::State::bypass { "Bypass", false }
editorSize
Dimensions lemons::plugin::State::editorSize { Dimensions::getDefault() }
Referenced by lemons::plugin::Editor< ContentComponentType, StateType,, >::Editor().
programs
ProgramManager lemons::plugin::State::programs
The documentation for this class was generated from the following file:
PluginState.h