Lemons: lemons::plugin::Processor< EngineType, StateType,, > Class Template Reference
lemons::plugin::Processor< EngineType, StateType,, > Class Template Reference
Plugins » lemons_plugin » Processors
A processor class that can simply be told the templated engine type and the state type, and takes care of instantiating a float and double one and passing them to the ProcessorBase class.
Public Types
using BusesProperties = juce::AudioProcessor::BusesProperties
using BusProperties = juce::AudioProcessor::BusProperties
Public Member Functions
Processor (const BusesProperties &busesLayout=getDefaultBusesLayout(), const ProcessorAttributes &attributes=ProcessorAttributes::fromProjectDefines())
Creates a processor with the specified bus layout.
Processor (const PluginMetadata &metadata)
Creates a processor from the provided metadata object.
ProcessorAttributes getAttributes () const noexcept
Returns the current state of the ProcessorAttributes object.
ToggleParameter & getBypass () const
Returns the plugin's bypass parameter.
juce::AudioProcessorParameter * getParameter (const String &parameterName) const
PluginMetadata getPluginMetadata () const
State & getState () noexcept
Returns the plugin's state object.
Version getVersion () const noexcept
Returns the Version object associated with this processor.
void loadState (const ValueTree &tree)
Reloads a previously saved state from a ValueTree.
ValueTree saveState (bool currentProgramOnly=false) const
Captures a snapshot of the processor's current state as a ValueTree.
Static Public Member Functions
static BusesProperties getDefaultBusesLayout ()
Returns a BusesLayout with stereo in and out buses that are enabled by default.
Protected Member Functions
basic_processor_editor_funcs Interacting with the editor
void callEditorMethod (std::function< void(juce::AudioProcessorEditor &)> func) const
Asynchronously calls a method of the current editor, if there is one, on the message thread.
void repaintEditor () const
Repaints the editor, if one exists.
Static Protected Member Functions
buses_properties_serializing Serializing BusesProperties
static BusesProperties busesPropertiesFromValueTree (const ValueTree &tree)
static ValueTree busesPropertiesToValueTree (const BusesProperties &properties)
Protected Attributes
const EditorAttributes editorAttributes
StateType pluginState
The plugin's state object.
Detailed Description
template<template< typename SampleType > class EngineType, typename StateType, LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >), LEMONS_MUST_INHERIT_FROM(StateType, State)>
class lemons::plugin::Processor< EngineType, StateType,, >
A processor class that can simply be told the templated engine type and the state type, and takes care of instantiating a float and double one and passing them to the ProcessorBase class.
Example usage:
using namespace lemons;
template<typename SampleType>
struct MyEngine : dsp::Engine<SampleType>
{
    // implement your audio processing here...
};
struct MyState : plugin::State
{
    // add your parameters here...
};
using MyPluginProcessor = plugin::Processor< MyEngine, MyState >;
By default, this processor class does not have an editor; use the ProcessorWithEditor class to create a processor with an editor.
Template Parameters
EngineType A class template for your plugin's engine class. This type must inherit from Engine.
StateType The type of the plugin's state object. This type must inherit from State.
See also
ProcessorBase, Engine, ProcessorWithEditor
Member Typedef Documentation
BusesProperties
using lemons::plugin::BasicProcessor::BusesProperties = juce::AudioProcessor::BusesProperties inherited
BusProperties
using lemons::plugin::BasicProcessor::BusProperties = juce::AudioProcessor::BusProperties inherited
Constructor & Destructor Documentation
Processor() [1/2]
template<template< typename SampleType > class EngineType, typename StateType , LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >) , LEMONS_MUST_INHERIT_FROM(StateType, State) > lemons::plugin::Processor< EngineType, StateType,, >::Processor (const BusesProperties & busesLayout = getDefaultBusesLayout(), const ProcessorAttributes & attributes = ProcessorAttributes::fromProjectDefines()) explicit
Creates a processor with the specified bus layout.
Processor() [2/2]
template<template< typename SampleType > class EngineType, typename StateType , LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >) , LEMONS_MUST_INHERIT_FROM(StateType, State) > lemons::plugin::Processor< EngineType, StateType,, >::Processor (const PluginMetadata & metadata) explicit
Creates a processor from the provided metadata object.
For this constructor to work, your StateType must accept the following constructor signature:
class StateType : public State
{
    StateType (const ParameterLayout&);
};
Member Function Documentation
busesPropertiesFromValueTree()
static BusesProperties lemons::plugin::BasicProcessor::busesPropertiesFromValueTree (const ValueTree & tree) static protected inherited
busesPropertiesToValueTree()
static ValueTree lemons::plugin::BasicProcessor::busesPropertiesToValueTree (const BusesProperties & properties) static protected inherited
callEditorMethod()
void lemons::plugin::BasicProcessor::callEditorMethod (std::function< void(juce::AudioProcessorEditor &)> func) const protected inherited
Asynchronously calls a method of the current editor, if there is one, on the message thread.
Internally, this uses the Juce MessageManager's callAsync method. Calling this on the audio thread should be avoided at all costs. I would personally only use this method in setStateInformation().
getAttributes()
ProcessorAttributes lemons::plugin::ProcessorBase::getAttributes () const noexcept inherited
Returns the current state of the ProcessorAttributes object.
Referenced by lemons::plugin::Processor< EngineType, StateType,, >::getPluginMetadata().
getBypass()
ToggleParameter & lemons::plugin::ProcessorBase::getBypass () const inherited
Returns the plugin's bypass parameter.
getDefaultBusesLayout()
static BusesProperties lemons::plugin::BasicProcessor::getDefaultBusesLayout () static inherited
Returns a BusesLayout with stereo in and out buses that are enabled by default.
getParameter()
juce::AudioProcessorParameter * lemons::plugin::BasicProcessor::getParameter (const String & parameterName) const inherited
getPluginMetadata()
template<template< typename SampleType > class EngineType, typename StateType , LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >) , LEMONS_MUST_INHERIT_FROM(StateType, State) > PluginMetadata lemons::plugin::Processor< EngineType, StateType,, >::getPluginMetadata () const
References lemons::plugin::Processor< EngineType, StateType,, >::editorAttributes, lemons::plugin::ProcessorBase::getAttributes(), lemons::plugin::Processor< EngineType, StateType,, >::pluginState, and lemons::Version::projectVersion().
getState()
State & lemons::plugin::ProcessorBase::getState () noexcept inherited
Returns the plugin's state object.
getVersion()
Version lemons::plugin::ProcessorBase::getVersion () const noexcept inherited
Returns the Version object associated with this processor.
loadState()
void lemons::plugin::ProcessorBase::loadState (const ValueTree & tree) inherited
Reloads a previously saved state from a ValueTree.
repaintEditor()
void lemons::plugin::BasicProcessor::repaintEditor () const protected inherited
Repaints the editor, if one exists.
This is a utility function that uses callEditorMethod() under the hood. Calling this on the audio thread should be avoided at all costs.
saveState()
ValueTree lemons::plugin::ProcessorBase::saveState (bool currentProgramOnly = false) const inherited
Captures a snapshot of the processor's current state as a ValueTree.
Member Data Documentation
editorAttributes
template<template< typename SampleType > class EngineType, typename StateType , LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >) , LEMONS_MUST_INHERIT_FROM(StateType, State) > const EditorAttributes lemons::plugin::Processor< EngineType, StateType,, >::editorAttributes protected
Referenced by lemons::plugin::Processor< EngineType, StateType,, >::getPluginMetadata().
pluginState
template<template< typename SampleType > class EngineType, typename StateType , LEMONS_MUST_INHERIT_FROM(EngineType< float >, dsp::Engine< float >) , LEMONS_MUST_INHERIT_FROM(StateType, State) > StateType lemons::plugin::Processor< EngineType, StateType,, >::pluginState protected
The plugin's state object.
Referenced by lemons::plugin::Processor< EngineType, StateType,, >::getPluginMetadata().
The documentation for this class was generated from the following file:
Plugins/lemons_plugin/processors/Processors.h