Lemons: lemons::serializing Namespace Reference
lemons::serializing Namespace Reference
Common » lemons_core » eventsCommon » lemons_serializing » | DataSynchronizerCommon » lemons_serializing » | SerializableDataCommon » lemons_serializing » | SerializingCommon » lemons_serializing » Serializing » | SpecializationsCommon » lemons_serializing » Serializing » Specializations » | containersCommon » lemons_serializing » Serializing » Specializations » | mapsCommon » lemons_serializing » Serializing » | ValueTreeToJsonCommon » lemons_serializing » | toggler
Classes
struct ContainerInterface
Interface that defines how a TreeReflector can resize a given container during deserialization.
class DataSynchronizer
Keeps two copies of an object inheriting from SerializableData in sync.
struct FileContents
A wrapper around a File that, when serializing, loads and saves the file's entire contents.
struct isContainer
Template struct that that indicates to TreeReflector whether a given type is a container.
struct isContainer< juce::Array< ElementType > >
Specifies that any specialization of juce::Array is a serializable container.
struct isContainer< juce::OwnedArray< ElementType > >
Specifies that any specialization of juce::OwnedArray is a serializable container.
struct isContainer< juce::StringArray >
Specifies that juce::StringArray is a serializable container.
struct isContainer< std::array< ElementType, size > >
Specifies that any specialization of std::array is a serializable container.
struct isContainer< std::deque< ElementType > >
Specifies that any specialization of std::deque is a serializable container.
struct isContainer< std::forward_list< ElementType > >
Specifies that any specialization of std::forward_list is a serializable container.
struct isContainer< std::list< ElementType > >
Specifies that any specialization of std::list is a serializable container.
struct isContainer< std::vector< ElementType > >
Specifies that any specialization of std::vector is a serializable container.
struct isMap
Template struct that indicates to TreeReflector whether a given type is a map.
struct isMap< juce::StringPairArray >
struct JuceArrayInterface
Container interface that provides support for serializing juce::Arrays with TreeReflector.
struct JuceOwnedArrayInterface
Container interface that provides support for serializing juce::OwnedArrays with TreeReflector.
struct LambdaContainerInterface
Provides a slightly slicker interface to ContainerInterface, allowing you to supply a lambda function to resize your container.
struct MapInterface
struct MapInterfaceBase
class NonrealtimeMutatable
class RealtimeMutatable
struct StdArrayInterface
Container interface that provides support for serializing std::arrays with TreeReflector.
struct STLContainerInterface
Container interface that provides support for serializing most STL containers with TreeReflector.
struct StringArrayInterface
Container interface that provides support for serializing juce::StringArrays with TreeReflector.
struct StringPairArrayInterface
struct Toggler
Class that manages several versions of the state of a serializable object and allows you to switch between them.
struct TogglerInterface
Interface that all Togglers implement to be able to access one without knowing its template arguments.
Functions
void copy (SerializableData &dest, SerializableData &source)
Copies from one serializable object to another by serializing the source object to a ValueTree, then deserializing the dest object from that tree.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType createCopy (ObjectType &objectToCopy)
Creates a copy of a serializable object by deserializing from the state of the source object.
void fromBinary (const juce::MemoryBlock &data, SerializableData &dest)
Deserializes an object from a juce::MemoryBlock.
template<typename IntegerType >
void fromBinary (const void *data, IntegerType dataSizeInBytes, SerializableData &dest)
Deserializes an object from some arbitrary opaque binary data.
void fromBinary (const void *data, size_t dataSizeInBytes, SerializableData &dest)
Deserializes an object from some arbitrary opaque binary data.
void fromBinary (File file, SerializableData &dest)
Deserializes an object from a file.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromBinaryCreate (const juce::MemoryBlock &data)
Creates a new object from the state saved in the MemoryBlock.
template<typename ObjectType , typename IntegerType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromBinaryCreate (const void *data, IntegerType dataSizeInBytes)
Creates a new object from the state saved in the opaque binary data.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromBinaryCreate (const void *data, size_t dataSizeInBytes)
Creates a new object from the state saved in the opaque binary data.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromBinaryCreate (File file)
Creates a new object from the state saved in the file.
void fromJSON (const File &file, SerializableData &dest)
Deserializes an object from a JSON file.
void fromJSON (const String &jsonText, SerializableData &dest)
Deserializes an object from a JSON string.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromJSONCreate (const File &file)
Creates a new object from the state saved in the JSON file.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromJSONCreate (const String &jsonText)
Creates a new object from the state saved in the JSON string.
void fromTree (const ValueTree &tree, SerializableData &data)
Deserializes an object from a ValueTree.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromTreeCreate (const ValueTree &tree)
Creates a new object from the state saved in the ValueTree.
template<>
String fromVar (const juce::var &var)
Explicitly calls juce::var::toString().
template<typename Type >
Type fromVar (const juce::var &var)
Implement this function and toVar() for any custom type to allow easily serialization using TreeReflector::add().
void fromXML (const File &xmlFile, SerializableData &dest)
Deserializes an object from an XML file.
void fromXML (const juce::XmlElement &xml, SerializableData &dest)
Deserializes an object from an XML element.
void fromXML (std::unique_ptr< juce::XmlElement > xml, SerializableData &dest)
Deserializes an object from an XML element.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromXMLCreate (const File &xmlFile)
Creates a new object from the state saved in the XML file.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromXMLCreate (const juce::XmlElement &xml)
Creates a new object from the state saved in the XML element.
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) >
ObjectType fromXMLCreate (std::unique_ptr< juce::XmlElement > xml)
Creates a new object from the state saved in the XML element.
template<typename ContainerType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (ContainerType &)
Template function that returns an instance of the correct ContainerInterface for the given container.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (juce::Array< ElementType > &container)
Returns an instance of JuceArrayInterface for the given juce::Array.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (juce::OwnedArray< ElementType > &container)
Returns an instance of JuceOwnedArrayInterface for the given juce::OwnedArray.
std::unique_ptr< ContainerInterface > getInterfaceForContainer (juce::StringArray &container)
Returns an instance of StringArrayInterface for the given juce::StringArray.
template<typename ElementType , size_t size>
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::array< ElementType, size > &container)
Returns an instance of StdArrayInterface for the given std::array.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::deque< ElementType > &container)
Returns an instance of STLContainerInterface for the given std::deque.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::forward_list< ElementType > &container)
Returns an instance of STLContainerInterface for the given std::forward_list.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::list< ElementType > &container)
Returns an instance of STLContainerInterface for the given std::list.
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::vector< ElementType > &container)
Returns an instance of STLContainerInterface for the given std::vector.
template<>
std::unique_ptr< MapInterfaceBase > getInterfaceForMap (juce::StringPairArray &array)
template<typename MapType >
std::unique_ptr< MapInterfaceBase > getInterfaceForMap (MapType &)
void toBinary (SerializableData &data, File file)
Saves the state of an object to a file.
void toBinary (SerializableData &data, juce::MemoryBlock &dest)
Saves the state of an object to a juce::MemoryBlock.
String toJSON (SerializableData &source)
Serializes an object to a JSON string.
void toJSON (SerializableData &source, const File &file)
Serializes an object to a JSON file.
ValueTree toTree (SerializableData &data)
Serializes an object to a ValueTree.
template<>
juce::var toVar (const AudioBuffer< double > &buffer)
Serializes an AudioBuffer to a var.
template<>
juce::var toVar (const AudioBuffer< float > &buffer)
Serializes an AudioBuffer to a var.
template<>
juce::var toVar (const File &file)
Serializes a file as its path's String representation.
template<>
juce::var toVar (const juce::BigInteger &bigint)
Serializes a juce BigInteger.
template<>
juce::var toVar (const juce::Identifier &ident)
Serializes an Identifier.
template<>
juce::var toVar (const juce::Image &image)
Serializes a juce::Image object using the PNG image format.
template<>
juce::var toVar (const juce::IPAddress &address)
Serializes an IP address as a String.
template<>
juce::var toVar (const juce::MemoryBlock &block)
Serializes a MemoryBlock.
template<>
juce::var toVar (const juce::MidiBuffer &buffer)
Serializes a juce::MidiBuffer.
template<>
juce::var toVar (const juce::Point< float > &point)
Serializes a float Point.
template<>
juce::var toVar (const juce::Point< int > &point)
Serializes an integer Point.
template<>
juce::var toVar (const juce::RelativeTime &time)
Serializes a juce::RelativeTime object.
template<>
juce::var toVar (const juce::Time &time)
Serializes a juce::Time object by saving it as the number of milliseconds since the computing epoch.
template<>
juce::var toVar (const juce::URL &url)
Serializes a URL as a String.
template<>
juce::var toVar (const juce::Uuid &uuid)
Serializes a juce::Uuid as a String.
template<>
juce::var toVar (const size_t &data)
Serializes a size_t.
template<>
juce::var toVar (const std::string &string)
Serializes a std::string.
template<typename Type >
juce::var toVar (const Type &object)
Implement this function and fromVar() for any custom type to allow easily serialization using TreeReflector::add().
std::unique_ptr< juce::XmlElement > toXML (SerializableData &source)
Serializes an object to an XML element.
void toXML (SerializableData &source, const File &file)
Serializes an object to an XML file.
ValueTree valueTreeFromJSON (const String &jsonText)
Converts a JSON string to a ValueTree.
String valueTreeToJSON (const ValueTree &v)
Converts a ValueTree to a JSON string.
Function Documentation
copy()
void lemons::serializing::copy (SerializableData & dest, SerializableData & source)
Copies from one serializable object to another by serializing the source object to a ValueTree, then deserializing the dest object from that tree.
Referenced by createCopy().
createCopy()
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::createCopy (ObjectType & objectToCopy)
Creates a copy of a serializable object by deserializing from the state of the source object.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References copy().
fromBinary() [1/4]
void lemons::serializing::fromBinary (const juce::MemoryBlock & data, SerializableData & dest)
Deserializes an object from a juce::MemoryBlock.
fromBinary() [2/4]
template<typename IntegerType > void lemons::serializing::fromBinary (const void * data, IntegerType dataSizeInBytes, SerializableData & dest)
Deserializes an object from some arbitrary opaque binary data.
References fromBinary().
fromBinary() [3/4]
void lemons::serializing::fromBinary (const void * data, size_t dataSizeInBytes, SerializableData & dest)
Deserializes an object from some arbitrary opaque binary data.
fromBinary() [4/4]
void lemons::serializing::fromBinary (File file, SerializableData & dest)
Deserializes an object from a file.
Referenced by fromBinary(), and fromBinaryCreate().
fromBinaryCreate() [1/4]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromBinaryCreate (const juce::MemoryBlock & data)
Creates a new object from the state saved in the MemoryBlock.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromBinary().
fromBinaryCreate() [2/4]
template<typename ObjectType , typename IntegerType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromBinaryCreate (const void * data, IntegerType dataSizeInBytes)
Creates a new object from the state saved in the opaque binary data.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
fromBinaryCreate() [3/4]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromBinaryCreate (const void * data, size_t dataSizeInBytes)
Creates a new object from the state saved in the opaque binary data.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromBinary().
fromBinaryCreate() [4/4]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromBinaryCreate (File file)
Creates a new object from the state saved in the file.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromBinary().
fromJSON() [1/2]
void lemons::serializing::fromJSON (const File & file, SerializableData & dest)
Deserializes an object from a JSON file.
fromJSON() [2/2]
void lemons::serializing::fromJSON (const String & jsonText, SerializableData & dest)
Deserializes an object from a JSON string.
Referenced by fromJSONCreate().
fromJSONCreate() [1/2]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromJSONCreate (const File & file)
Creates a new object from the state saved in the JSON file.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
See also
valueTreeToJSON()
References fromJSON().
fromJSONCreate() [2/2]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromJSONCreate (const String & jsonText)
Creates a new object from the state saved in the JSON string.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
See also
valueTreeFromJSON()
References fromJSON().
fromTree()
void lemons::serializing::fromTree (const ValueTree & tree, SerializableData & data)
Deserializes an object from a ValueTree.
Referenced by fromTreeCreate(), and lemons::serializing::Toggler< 3 >::loadState().
fromTreeCreate()
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromTreeCreate (const ValueTree & tree)
Creates a new object from the state saved in the ValueTree.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromTree().
fromVar() [1/2]
template<> File lemons::serializing::fromVar (const juce::var & var)
Explicitly calls juce::var::toString().
Serializes a file as its path's String representation.
Deserializes an AudioBuffer from a var.
Serializes a juce::MidiBuffer.
Serializes a juce::Image object using the PNG image format.
Serializes a juce::RelativeTime object.
Serializes a juce::Time object by loading it as the number of milliseconds since the computing epoch.
Serializes a juce::Uuid as a String.
Serializes a std::string.
Serializes an IP address as a String.
Serializes a URL as a String.
Serializes a MemoryBlock.
Serializes an integer Point.
Serializes a float Point.
Serializes a juce BigInteger.
Serializes a size_t.
Serializes an Identifier.
This works by reading the contents of a String into binary form, using Base64 encoding.
Internally, this converts the var to a String, then uses juce's FlacAudioFormat to decode the String back into audio samples.
Internally, this converts the var to a String, then uses juce's FlacAudioFormat to decode the String back into audio samples.
Since juce's FlacAudioFormat is only available for float samples, the buffer is first decoded with float samples and then converted to double samples for the final result.
This method may be platform-dependant. I recommend using the FileContents struct to reliably serialize files' contents instead of their paths.
Explicitly calls juce::var::toString().
This function must load the complete state of your object from a juce::var. Your object type must be default-constructable.
This function must do the exact opposite of what your implementation of toVar() for your type does.
Usually what this boils down to is creating a default-constructed instance of your object, then setting properties or relevant data members programmatically based on parsing the encoded String returned from the var.
Several examples of implementations of this function can be found in lemons_serializing/Serializing/Specializations/VarSpecializations.cpp.
As a general rule, you shouldn't need to implement toVar() and fromVar() for a type if that type inherits from SerializableData; and, conversely, you should implement toVar() and fromVar() for a type if it needs to be serialized and doesn't inherit from SerializableData. You should rarely, if ever, need both for a single type. If your type has multiple distinct pieces of data or steps to its serialization logic, it is usually preferable to have your type inherit from SerializableData.
// example implementation:
namespace lemons
{
    template<>
    juce::var toVar (MyCustomType& object)
    {
        // implement your conversion logic here...
    }
    template<>
    MyCustomType fromVar (juce::var var)
    {
        // implement your conversion logic here...
    }
}
// example usage:
struct SomethingSerializable : lemons::SerializableData
{
    void serialize (TreeReflector& ref) final
    {
        // TreeReflector will internally call toVar to save your object and fromVar to load your object
        ref.add ("MyCustomData", data);
    }
    MyCustomType data;
};
See also
toVar(), SerializableData, TreeReflector
fromVar() [2/2]
template<typename Type > Type lemons::serializing::fromVar (const juce::var & var)
Implement this function and toVar() for any custom type to allow easily serialization using TreeReflector::add().
Explicitly calls juce::var::toString().
This function must load the complete state of your object from a juce::var. Your object type must be default-constructable.
This function must do the exact opposite of what your implementation of toVar() for your type does.
Usually what this boils down to is creating a default-constructed instance of your object, then setting properties or relevant data members programmatically based on parsing the encoded String returned from the var.
Several examples of implementations of this function can be found in lemons_serializing/Serializing/Specializations/VarSpecializations.cpp.
As a general rule, you shouldn't need to implement toVar() and fromVar() for a type if that type inherits from SerializableData; and, conversely, you should implement toVar() and fromVar() for a type if it needs to be serialized and doesn't inherit from SerializableData. You should rarely, if ever, need both for a single type. If your type has multiple distinct pieces of data or steps to its serialization logic, it is usually preferable to have your type inherit from SerializableData.
// example implementation:
namespace lemons
{
    template<>
    juce::var toVar (MyCustomType& object)
    {
        // implement your conversion logic here...
    }
    template<>
    MyCustomType fromVar (juce::var var)
    {
        // implement your conversion logic here...
    }
}
// example usage:
struct SomethingSerializable : lemons::SerializableData
{
    void serialize (TreeReflector& ref) final
    {
        // TreeReflector will internally call toVar to save your object and fromVar to load your object
        ref.add ("MyCustomData", data);
    }
    MyCustomType data;
};
See also
toVar(), SerializableData, TreeReflector
fromXML() [1/3]
void lemons::serializing::fromXML (const File & xmlFile, SerializableData & dest)
Deserializes an object from an XML file.
fromXML() [2/3]
void lemons::serializing::fromXML (const juce::XmlElement & xml, SerializableData & dest)
Deserializes an object from an XML element.
Referenced by fromXMLCreate().
fromXML() [3/3]
void lemons::serializing::fromXML (std::unique_ptr< juce::XmlElement > xml, SerializableData & dest)
Deserializes an object from an XML element.
fromXMLCreate() [1/3]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromXMLCreate (const File & xmlFile)
Creates a new object from the state saved in the XML file.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromXML().
fromXMLCreate() [2/3]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromXMLCreate (const juce::XmlElement & xml)
Creates a new object from the state saved in the XML element.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromXML().
fromXMLCreate() [3/3]
template<typename ObjectType , LEMONS_MUST_INHERIT_FROM(ObjectType, SerializableData) > ObjectType lemons::serializing::fromXMLCreate (std::unique_ptr< juce::XmlElement > xml)
Creates a new object from the state saved in the XML element.
Template Parameters
ObjectType The type of object to create. This type must inherit from SerializableData and must be default-constructable.
References fromXML().
getInterfaceForContainer() [1/9]
template<typename ContainerType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (ContainerType &)
Template function that returns an instance of the correct ContainerInterface for the given container.
Implement this if you want to be able to serialize a custom container type with a single TreeReflector::add() call.
    To add support for a custom container type to TreeReflector::add():
    - Implement a subclass of serializing::ContainerInterface with the correct resizing logic for your cotainer;
    - Implement a specialization ofserializing::getContainerForInterface() that returns an instance of your custom interface;
    - Specialize the serializing::isContainer struct for your type and make the specialization inherit from std::true_type.
    In addition, your custom container type must have begin() and end() functions -- ie, it must be compatable with range-based for loops.
    The elements of your container must also be valid TreeReflector::add() calls -- ie, if they don't inherit SerializableData, you must implement toVar() and fromVar() for the container's element type as well.
    Here is an example implementation for a custom type:
    template<typename ElementType>
    struct MyContainerType
    {
        ElementType* begin();
        ElementType* end();
        void setSize (int);
    };
    // Step 1: implement container interface
    // This tells the TreeReflector how to resize your container
    template<typename ElementType>
    struct MyContainerInterface : lemons::serializing::ContainerInterface
    {
        using Container = MyContainerType<ElementType>;
        MyContainerInterface (Container& c) : container (c) { }
    private:
        void resize (int newSize) final
    {
        container.setSize (newSize);
    }
        Container& container;
    };
    // Step 2: implement getInterfaceForContainer()
    // This creates an instance of your container interface for the TreeReflector to use
    template < typename ElementType >
    std::unique_ptr< ContainerInterface > getInterfaceForContainer (MyContainerType< ElementType >& container)
    {
        return std::make_unique< MyContainerInterface< ElementType > > (container);
    }
    // Step 3: implement isContainer
    // This tells TreeReflector that any specialization of your container type is a kind of container
    template < typename ElementType >
    struct isContainer< MyContainerType< ElementType > > : std::true_type
    {
    };
Template Parameters
ContainerType The fully specialized container type – for example, std::vector<int> or juce::Array<float>.
See also
TreeReflector, ContainerInterface, isContainer
getInterfaceForContainer() [2/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (juce::Array< ElementType > & container)
Returns an instance of JuceArrayInterface for the given juce::Array.
getInterfaceForContainer() [3/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (juce::OwnedArray< ElementType > & container)
Returns an instance of JuceOwnedArrayInterface for the given juce::OwnedArray.
getInterfaceForContainer() [4/9]
std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (juce::StringArray & container)
Returns an instance of StringArrayInterface for the given juce::StringArray.
getInterfaceForContainer() [5/9]
template<typename ElementType , size_t size> std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (std::array< ElementType, size > & container)
Returns an instance of StdArrayInterface for the given std::array.
getInterfaceForContainer() [6/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (std::deque< ElementType > & container)
Returns an instance of STLContainerInterface for the given std::deque.
getInterfaceForContainer() [7/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (std::forward_list< ElementType > & container)
Returns an instance of STLContainerInterface for the given std::forward_list.
getInterfaceForContainer() [8/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (std::list< ElementType > & container)
Returns an instance of STLContainerInterface for the given std::list.
getInterfaceForContainer() [9/9]
template<typename ElementType > std::unique_ptr<ContainerInterface> lemons::serializing::getInterfaceForContainer (std::vector< ElementType > & container)
Returns an instance of STLContainerInterface for the given std::vector.
getInterfaceForMap() [1/2]
template<> std::unique_ptr<MapInterfaceBase> lemons::serializing::getInterfaceForMap (juce::StringPairArray & array)
getInterfaceForMap() [2/2]
template<typename MapType > std::unique_ptr<MapInterfaceBase> lemons::serializing::getInterfaceForMap (MapType &)
toBinary() [1/2]
void lemons::serializing::toBinary (SerializableData & data, File file)
Saves the state of an object to a file.
Internally, this method calls juce::ValueTree::writeToStream(), so the data is stored as an arbitrary binary encoding of a ValueTree, not necessarily a common format like XML or JSON.
Use the XML- and JSON-specific functions in this namespace to explicitly use either format.
See also
toXML(), toJSON()
toBinary() [2/2]
void lemons::serializing::toBinary (SerializableData & data, juce::MemoryBlock & dest)
Saves the state of an object to a juce::MemoryBlock.
toJSON() [1/2]
String lemons::serializing::toJSON (SerializableData & source)
Serializes an object to a JSON string.
toJSON() [2/2]
void lemons::serializing::toJSON (SerializableData & source, const File & file)
Serializes an object to a JSON file.
toTree()
ValueTree lemons::serializing::toTree (SerializableData & data)
Serializes an object to a ValueTree.
Referenced by lemons::serializing::Toggler< 3 >::saveState().
toVar() [1/18]
template<> juce::var lemons::serializing::toVar (const AudioBuffer< double > & buffer)
Serializes an AudioBuffer to a var.
Since juce's FlacAudioFormat is only available for float samples, this first converts the buffer to floats and then uses juce::FlacAudioFormat to write the buffer's contents to a String.
toVar() [2/18]
template<> juce::var lemons::serializing::toVar (const AudioBuffer< float > & buffer)
Serializes an AudioBuffer to a var.
Internally, this uses juce's FlacAudioFormat to write the buffer's contents into a String.
toVar() [3/18]
template<> juce::var lemons::serializing::toVar (const File & file)
Serializes a file as its path's String representation.
This method may be platform-dependant. I recommend using the FileContents struct to reliably serialize files' contents instead of their paths.
toVar() [4/18]
template<> juce::var lemons::serializing::toVar (const juce::BigInteger & bigint)
Serializes a juce BigInteger.
toVar() [5/18]
template<> juce::var lemons::serializing::toVar (const juce::Identifier & ident)
Serializes an Identifier.
toVar() [6/18]
template<> juce::var lemons::serializing::toVar (const juce::Image & image)
Serializes a juce::Image object using the PNG image format.
toVar() [7/18]
template<> juce::var lemons::serializing::toVar (const juce::IPAddress & address)
Serializes an IP address as a String.
toVar() [8/18]
template<> juce::var lemons::serializing::toVar (const juce::MemoryBlock & block)
Serializes a MemoryBlock.
This works by writing the contents of the memory block to a String use Base64 encoding.
toVar() [9/18]
template<> juce::var lemons::serializing::toVar (const juce::MidiBuffer & buffer)
Serializes a juce::MidiBuffer.
toVar() [10/18]
template<> juce::var lemons::serializing::toVar (const juce::Point< float > & point)
Serializes a float Point.
toVar() [11/18]
template<> juce::var lemons::serializing::toVar (const juce::Point< int > & point)
Serializes an integer Point.
toVar() [12/18]
template<> juce::var lemons::serializing::toVar (const juce::RelativeTime & time)
Serializes a juce::RelativeTime object.
toVar() [13/18]
template<> juce::var lemons::serializing::toVar (const juce::Time & time)
Serializes a juce::Time object by saving it as the number of milliseconds since the computing epoch.
toVar() [14/18]
template<> juce::var lemons::serializing::toVar (const juce::URL & url)
Serializes a URL as a String.
toVar() [15/18]
template<> juce::var lemons::serializing::toVar (const juce::Uuid & uuid)
Serializes a juce::Uuid as a String.
toVar() [16/18]
template<> juce::var lemons::serializing::toVar (const size_t & data)
Serializes a size_t.
toVar() [17/18]
template<> juce::var lemons::serializing::toVar (const std::string & string)
Serializes a std::string.
toVar() [18/18]
template<typename Type > juce::var lemons::serializing::toVar (const Type & object)
Implement this function and fromVar() for any custom type to allow easily serialization using TreeReflector::add().
This function must save the complete state of your object either directly to a juce::var or to a type that is implicitly convertable to juce::var (ie, float, int, juce::String, etc.).
This function must do the exact opposite of what your implementation of fromVar() for your type does.
Usually what this boils down to is encoding your object into a juce::String in some way, which can then be implicitly converted to a juce::var.
Several examples of implementations of this function can be found in lemons_serializing/Serializing/Specializations/VarSpecializations.cpp.
As a general rule, you shouldn't need to implement toVar() and fromVar() for a type if that type inherits from SerializableData; and, conversely, you should implement toVar() and fromVar() for a type if it needs to be serialized and doesn't inherit from SerializableData. You should rarely, if ever, need both for a single type. If your type has multiple distinct pieces of data or steps to its serialization logic, it is usually preferable to have your type inherit from SerializableData.
// example implementation:
namespace lemons
{
    template<>
    juce::var toVar (MyCustomType& object)
    {
        // implement your conversion logic here...
    }
    template<>
    MyCustomType fromVar (juce::var var)
    {
        // implement your conversion logic here...
    }
}
// example usage:
struct SomethingSerializable : lemons::SerializableData
{
    void serialize (TreeReflector& ref) final
    {
        // TreeReflector will internally call toVar to save your object and fromVar to load your object
        ref.add ("MyCustomData", data);
    }
    MyCustomType data;
};
See also
fromVar(), SerializableData, TreeReflector
toXML() [1/2]
std::unique_ptr<juce::XmlElement> lemons::serializing::toXML (SerializableData & source)
Serializes an object to an XML element.
toXML() [2/2]
void lemons::serializing::toXML (SerializableData & source, const File & file)
Serializes an object to an XML file.
valueTreeFromJSON()
ValueTree lemons::serializing::valueTreeFromJSON (const String & jsonText)
Converts a JSON string to a ValueTree.
valueTreeToJSON()
String lemons::serializing::valueTreeToJSON (const ValueTree & v)
Converts a ValueTree to a JSON string.