Lemons: lemons::TreeReflectorHelpers Namespace Reference
lemons::TreeReflectorHelpers Namespace Reference
Classes
struct ContainerInterface
struct JuceOwnedArrayInterface
struct StdArrayInterface
Functions
template<typename ContainerType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (ContainerType &)
template<class Type >
constexpr bool isContainer ()
template<typename ElementType >
std::unique_ptr< ContainerInterface > getInterfaceForContainer (juce::OwnedArray< ElementType > &container)
template<typename ElementType , size_t size>
std::unique_ptr< ContainerInterface > getInterfaceForContainer (std::array< ElementType, size > &container)
template<typename ElementType , size_t size>
constexpr bool isContainer (std::array< ElementType, size > &)
template<typename ElementType >
constexpr bool isContainer (std::vector< ElementType > &)
template<typename Type >
constexpr bool isSerializable ()
template<typename Type >
Type toEnum (const juce::var &var)
template<typename Type >
juce::var fromEnum (Type value)
template<typename Type >
void loadObject (const ValueTree &tree, const String &propertyName, Type &object)
template<typename Type >
void saveObject (ValueTree &tree, const String &propertyName, Type &object)
void loadValueTree (const ValueTree &tree, const String &propertyName, ValueTree &data)
void saveValueTree (ValueTree &tree, const String &propertyName, ValueTree &data)
String propertyNameToContainerName (const String &propertyName)
String makePropertyNameForElement (const String &propertyName, int &index)
int getNumElementsOfType (const String &propertyName, const ValueTree &tree)
template<class ContainerType >
void addContainer (TreeReflector &ref, ContainerType &container, const String &propertyName)
Function Documentation
getInterfaceForContainer() [1/3]
template<typename ContainerType > std::unique_ptr< ContainerInterface > lemons::TreeReflectorHelpers::getInterfaceForContainer (ContainerType &)
isContainer() [1/3]
template<class Type > constexpr bool lemons::TreeReflectorHelpers::isContainer () constexpr
getInterfaceForContainer() [2/3]
template<typename ElementType > std::unique_ptr< ContainerInterface > lemons::TreeReflectorHelpers::getInterfaceForContainer (juce::OwnedArray< ElementType > & container)
getInterfaceForContainer() [3/3]
template<typename ElementType , size_t size> std::unique_ptr< ContainerInterface > lemons::TreeReflectorHelpers::getInterfaceForContainer (std::array< ElementType, size > & container)
isContainer() [2/3]
template<typename ElementType , size_t size> constexpr bool lemons::TreeReflectorHelpers::isContainer (std::array< ElementType, size > &) constexpr
isContainer() [3/3]
template<typename ElementType > constexpr bool lemons::TreeReflectorHelpers::isContainer (std::vector< ElementType > &) constexpr
isSerializable()
template<typename Type > constexpr bool lemons::TreeReflectorHelpers::isSerializable () constexpr
toEnum()
template<typename Type > Type lemons::TreeReflectorHelpers::toEnum (const juce::var & var)
fromEnum()
template<typename Type > juce::var lemons::TreeReflectorHelpers::fromEnum (Type value)
Referenced by saveObject().
loadObject()
template<typename Type > void lemons::TreeReflectorHelpers::loadObject (const ValueTree & tree, const String & propertyName, Type & object)
saveObject()
template<typename Type > void lemons::TreeReflectorHelpers::saveObject (ValueTree & tree, const String & propertyName, Type & object)
References fromEnum(), and lemons::toVar().
loadValueTree()
void lemons::TreeReflectorHelpers::loadValueTree (const ValueTree & tree, const String & propertyName, ValueTree & data)
saveValueTree()
void lemons::TreeReflectorHelpers::saveValueTree (ValueTree & tree, const String & propertyName, ValueTree & data)
propertyNameToContainerName()
String lemons::TreeReflectorHelpers::propertyNameToContainerName (const String & propertyName)
makePropertyNameForElement()
String lemons::TreeReflectorHelpers::makePropertyNameForElement (const String & propertyName, int & index)
Referenced by addContainer().
getNumElementsOfType()
int lemons::TreeReflectorHelpers::getNumElementsOfType (const String & propertyName, const ValueTree & tree)
Referenced by addContainer().
addContainer()
template<class ContainerType > void lemons::TreeReflectorHelpers::addContainer (TreeReflector & ref, ContainerType & container, const String & propertyName)
References lemons::TreeReflector::add(), getNumElementsOfType(), lemons::TreeReflector::getRawDataTree(), lemons::TreeReflector::isLoading(), and makePropertyNameForElement().