Lemons: lemons::serializing::TreeReflectorHelpers Namespace Reference
lemons::serializing::TreeReflectorHelpers Namespace Reference
Functions
template<class ContainerType >
void addContainer (TreeReflector &ref, ContainerType &container, const String &propertyName)
Adds a container to the given TreeReflector.
template<typename Type >
juce::var fromEnum (Type value)
Converts an enum type to a juce::var.
int getNumElementsOfType (const String &propertyName, const ValueTree &tree)
Detects how many elements a given container contains.
template<typename Type >
constexpr bool isSerializable ()
Returns true if the given object inherits from SerializableData and is not const.
template<typename Type >
void loadObject (const ValueTree &tree, const String &propertyName, Type &object)
Restores the state of an object by retrieving the specified named property from the ValueTree, if it exists.
void loadValueTree (const ValueTree &tree, const String &propertyName, ValueTree &data)
Restores the state of a child ValueTree with the specified name.
String makePropertyNameForElement (const String &propertyName, int &index)
Transforms a passed generic container element name and container index into a unique name for a given object.
String propertyNameToContainerName (const String &propertyName)
Transforms the name of a single container element to a name for the container's sub-node.
template<typename Type >
void saveObject (ValueTree &tree, const String &propertyName, Type &object)
Saves the state of an object by writing its juce::var representation to the ValueTree with the specified property name.
void saveValueTree (ValueTree &tree, const String &propertyName, ValueTree &data)
Saves the state of a child ValueTree to a sub-node in the parent tree with the specified name.
template<typename Type >
Type toEnum (const juce::var &var)
Converts a juce::var to a specified enum type.
Function Documentation
addContainer()
template<class ContainerType > void lemons::serializing::TreeReflectorHelpers::addContainer (TreeReflector & ref, ContainerType & container, const String & propertyName)
Adds a container to the given TreeReflector.
Used for both loading and saving.
References lemons::TreeReflector::add(), lemons::serializing::getInterfaceForContainer(), getNumElementsOfType(), lemons::TreeReflector::getRawDataTree(), lemons::TreeReflector::isLoading(), and makePropertyNameForElement().
fromEnum()
template<typename Type > juce::var lemons::serializing::TreeReflectorHelpers::fromEnum (Type value)
Converts an enum type to a juce::var.
Referenced by saveObject().
getNumElementsOfType()
int lemons::serializing::TreeReflectorHelpers::getNumElementsOfType (const String & propertyName, const ValueTree & tree)
Detects how many elements a given container contains.
Uses the same transformation as makePropertyNameForElement() and counts how many valid indices it can find corresponding to existing property names.
See also
makePropertyNameForElement()
Referenced by addContainer().
isSerializable()
template<typename Type > constexpr bool lemons::serializing::TreeReflectorHelpers::isSerializable () constexpr
Returns true if the given object inherits from SerializableData and is not const.
See also
SerializableData
loadObject()
template<typename Type > void lemons::serializing::TreeReflectorHelpers::loadObject (const ValueTree & tree, const String & propertyName, Type & object)
Restores the state of an object by retrieving the specified named property from the ValueTree, if it exists.
See also
serializing::fromVar(), toEnum()
loadValueTree()
void lemons::serializing::TreeReflectorHelpers::loadValueTree (const ValueTree & tree, const String & propertyName, ValueTree & data)
Restores the state of a child ValueTree with the specified name.
makePropertyNameForElement()
String lemons::serializing::TreeReflectorHelpers::makePropertyNameForElement (const String & propertyName, int & index)
Transforms a passed generic container element name and container index into a unique name for a given object.
The transformation is:
{propertyName}_{index}
For example, passing "Item" with an index of 3 will return "Item_3".
This function also increments the referenced index each time it's called.
Referenced by addContainer().
propertyNameToContainerName()
String lemons::serializing::TreeReflectorHelpers::propertyNameToContainerName (const String & propertyName)
Transforms the name of a single container element to a name for the container's sub-node.
This simply appends an "s" to the passed propertyName.
For example, passing "Item" will return "Items".
saveObject()
template<typename Type > void lemons::serializing::TreeReflectorHelpers::saveObject (ValueTree & tree, const String & propertyName, Type & object)
Saves the state of an object by writing its juce::var representation to the ValueTree with the specified property name.
See also
serializing::toVar(), fromEnum()
References fromEnum(), and lemons::serializing::toVar().
saveValueTree()
void lemons::serializing::TreeReflectorHelpers::saveValueTree (ValueTree & tree, const String & propertyName, ValueTree & data)
Saves the state of a child ValueTree to a sub-node in the parent tree with the specified name.
toEnum()
template<typename Type > Type lemons::serializing::TreeReflectorHelpers::toEnum (const juce::var & var)
Converts a juce::var to a specified enum type.