Lemons: lemons::alg Namespace Reference
lemons::alg Namespace Reference
Functions
template<class Container1 , class Container2 , class Callable >
constexpr void call_both (const Container1 &container1, const Container2 &container2, Callable &&callable)
template<class ContainerType , class T >
constexpr bool contains (const ContainerType &container, const T &value)
template<class ContainerType , class UnaryPredicate >
constexpr bool contains_if (const ContainerType &container, UnaryPredicate &&p)
template<class ContainerType , class T , class UnaryPredicate >
constexpr const T & contains_or (const ContainerType &container, const T &defaultValue, UnaryPredicate &&p)
template<class ContainerType , class T , class UnaryPredicate >
constexpr T & contains_or (const ContainerType &container, T &defaultValue, UnaryPredicate &&p)
template<class T , class ContainerType , class UnaryPredicate >
constexpr T contains_or_default (const ContainerType &container, UnaryPredicate &&p)
template<class T , class ContainerType , class UnaryPredicate >
constexpr T * contains_or_null (const ContainerType &container, UnaryPredicate &&p)
template<class ContainerType , class UnaryPredicate >
constexpr int num_of (const ContainerType &container, UnaryPredicate &&p)
template<class ContainerType >
constexpr void removeDuplicates (ContainerType &container)
template<typename T >
void removeDuplicates (juce::Array< T > &array)
template<class ContainerType >
constexpr void reverse (ContainerType &container)
template<class ContainerType >
constexpr void sort (ContainerType &container, bool forward=true)
template<class ContainerType , class Comparison >
constexpr void sort (ContainerType &container, Comparison &&predicate, bool forward=true)
Function Documentation
call_both()
template<class Container1 , class Container2 , class Callable > constexpr void lemons::alg::call_both (const Container1 & container1, const Container2 & container2, Callable && callable) constexpr
contains()
template<class ContainerType , class T > constexpr bool lemons::alg::contains (const ContainerType & container, const T & value) constexpr
contains_if()
template<class ContainerType , class UnaryPredicate > constexpr bool lemons::alg::contains_if (const ContainerType & container, UnaryPredicate && p) constexpr
contains_or() [1/2]
template<class ContainerType , class T , class UnaryPredicate > constexpr const T & lemons::alg::contains_or (const ContainerType & container, const T & defaultValue, UnaryPredicate && p) constexpr
contains_or() [2/2]
template<class ContainerType , class T , class UnaryPredicate > constexpr T & lemons::alg::contains_or (const ContainerType & container, T & defaultValue, UnaryPredicate && p) constexpr
contains_or_default()
template<class T , class ContainerType , class UnaryPredicate > constexpr T lemons::alg::contains_or_default (const ContainerType & container, UnaryPredicate && p) constexpr
contains_or_null()
template<class T , class ContainerType , class UnaryPredicate > constexpr T * lemons::alg::contains_or_null (const ContainerType & container, UnaryPredicate && p) constexpr
num_of()
template<class ContainerType , class UnaryPredicate > constexpr int lemons::alg::num_of (const ContainerType & container, UnaryPredicate && p) constexpr
removeDuplicates() [1/2]
template<class ContainerType > constexpr void lemons::alg::removeDuplicates (ContainerType & container) constexpr
removeDuplicates() [2/2]
template<typename T > void lemons::alg::removeDuplicates (juce::Array< T > & array)
reverse()
template<class ContainerType > constexpr void lemons::alg::reverse (ContainerType & container) constexpr
References reverse().
Referenced by reverse(), and sort().
sort() [1/2]
template<class ContainerType > constexpr void lemons::alg::sort (ContainerType & container, bool forward = true) constexpr
References reverse(), and sort().
sort() [2/2]
template<class ContainerType , class Comparison > constexpr void lemons::alg::sort (ContainerType & container, Comparison && predicate, bool forward = true) constexpr
References reverse(), and sort().
Referenced by sort().