Lemons: lemons::rsa Namespace Reference
lemons::rsa Namespace Reference
Functions
template<typename T >
T decryptObject (const String &encryptedString, const RSAKey &privateKey)
String decryptString (const String &encryptedString, const RSAKey &privateKey)
template<typename T >
String encryptObject (const T &object, const RSAKey &publicKey)
String encryptString (const String &stringToEncrypt, const RSAKey &publicKey)
void generateKeyPair (const juce::File &outputFile, int numBits=128, const juce::Array< int > &randomSeeds={})
Function Documentation
decryptObject()
template<typename T > T lemons::rsa::decryptObject (const String & encryptedString, const RSAKey & privateKey)
References decryptString().
decryptString()
String lemons::rsa::decryptString (const String & encryptedString, const RSAKey & privateKey)
Referenced by decryptObject().
encryptObject()
template<typename T > String lemons::rsa::encryptObject (const T & object, const RSAKey & publicKey)
References encryptString().
encryptString()
String lemons::rsa::encryptString (const String & stringToEncrypt, const RSAKey & publicKey)
Referenced by encryptObject().
generateKeyPair()
void lemons::rsa::generateKeyPair (const juce::File & outputFile, int numBits = 128, const juce::Array< int > & randomSeeds = {})