Lemons: lemons::TreeLoader Struct Reference
lemons::TreeLoader Struct Reference
Subclass of TreeReflector used for loading state.
#include <TreeReflector.h>
Public Member Functions
template<typename Type >
void add (const String &propertyName, Type &object)
Binds a named ValueTree property to a data member of your object.
template<typename Type >
void addLambdaSet (const String &propertyName, std::function< Type() > saveToTree, std::function< void(Type &) > loadFromTree)
Binds lambda functions for saving and loading a certain value to and from a named ValueTree property.
ValueTree & getRawDataTree ()
Returns a reference to this reflector's root ValueTree.
bool isLoading () const final
Returns true if this reflector is loading state.
bool isSaving () const
Returns true if this reflector is saving state.
TreeReflector (const ValueTree &treeToUse)
Creates a TreeReflector.
Detailed Description
Subclass of TreeReflector used for loading state.
See also
TreeReflector
Member Function Documentation
add()
template<typename Type > void lemons::TreeReflector::add (const String & propertyName, Type & object) inherited
Binds a named ValueTree property to a data member of your object.
Uses serializing::toVar() to save to the tree, and serializing::fromVar() to restore from the tree. Be careful not to use duplicate property names in the serialization logic for a single object! For example:
struct SomethingSerializable : lemons::SerializableData
{
    // we want to save this integer with our program's state
    int data;
    void serialize (TreeReflector& ref) final
    {
        // simply choose a property name -- and that's it!
        ref.add ("MyData", data);
    }
};
This also works for containers that have begin() and end() functions; for containers, the property name you pass should be the name of a single element in the container. For example:
struct SomethingSerializable : lemons::SerializableData
{
    std::vector<int> data;
    void serialize (TreeReflector& ref) final
    {
        ref.add ("Int", data);
    }
};
This will create a sub-tree in your object's ValueTree named "Ints", with properties "Int_1", "Int_2", "Int_3", etc. This works by iterating through each element of your container and calling add() on each of them – so the type of the elements of your container must have toVar() and fromVar() implemented.
Parameters
propertyName The name of the ValueTree property that this data member corresponds to. When saving, the juce::var-encoded version of the data member will be written to the tree using this property name. When loading, if the tree has a property with this name, it will be converted from juce::var back into your type and assigned to the data member. When adding a container, this should be the name of a single container element.
object Reference to the data member you wish to load/save.
See also
serializing::toVar(), serializing::fromVar()
References lemons::TreeReflector::isLoading().
Referenced by lemons::serializing::TreeReflectorHelpers::addContainer().
addLambdaSet()
template<typename Type > void lemons::TreeReflector::addLambdaSet (const String & propertyName, std::function< Type() > saveToTree, std::function< void(Type &) > loadFromTree) inherited
Binds lambda functions for saving and loading a certain value to and from a named ValueTree property.
This works similarly to add(), but provides the ability to fetch the value using a lambda, and call a lambda with the value retrieved from the tree. Internally, uses serializing::toVar() to save to the tree, and serializing::fromVar() to restore from the tree. Be careful not to use duplicate property names in the serialization logic for a single object! For example:
 struct SomethingSerializable : lemons::SerializableData
 {
    // maybe this function has side effects?
    void setData (int newData);
private:
    // we still want to save this integer with our program's state, but I want to call setData() when it's being loaded...
    int data;
    void serialize (TreeReflector& ref) final
    {
        // you can specify lambdas for retrieving and saving a property's value as a specified type (int)
        ref.addLambdaSet<int> ("MyData",
                                [&]{ return data; },
                                [&](int newData){ setData (newData); });
    }
 };
If you use this function with a container type, your lambdas must return/recieve the entire container by value. I recommend sticking to add() (or implementing custom logic) for containers.
Parameters
propertyName The name of the ValueTree property that this data corresponds to. When saving, the juce::var-encoded version of the object returned from the saveToTree function will be written to the tree using this property name. When loading, if the tree has a property with this name, it will be converted from juce::var back into your type and passed to the loadFromTree function.
saveToTree This lambda should return the current value of the data you wish to save.
loadFromTree This lambda will be called with the new value for this data when a new state is loaded.
See also
serializing::toVar(), serializing::fromVar()
References lemons::TreeReflector::isLoading().
getRawDataTree()
ValueTree& lemons::TreeReflector::getRawDataTree () inherited
Returns a reference to this reflector's root ValueTree.
Handle with care! The tree this function returns may already contain sub-nodes representing other serialized children of whatever object is serializing you at the moment...
Referenced by lemons::serializing::TreeReflectorHelpers::addContainer().
isLoading()
bool lemons::TreeLoader::isLoading () const final virtual
Returns true if this reflector is loading state.
Implements lemons::TreeReflector.
isSaving()
bool lemons::TreeReflector::isSaving () const inherited
Returns true if this reflector is saving state.
TreeReflector()
lemons::TreeReflector::TreeReflector explicit
Creates a TreeReflector.
Whether this reflector is loading or saving, it must be given a ValueTree to reference.
The documentation for this struct was generated from the following file:
TreeReflector.h