Lemons: lemons::TreeReflector Struct Reference
lemons::TreeReflector Struct Reference abstract
Utility class that provides a convenient API for assigning data members or lambdas to ValueTree properties for use in serializing logic.
#include <TreeReflector.h>
Public Member Functions
TreeReflector (const ValueTree &treeToUse)
Creates a TreeReflector.
virtual ~TreeReflector ()=default
Destructor.
template<typename Type >
void add (const String &propertyName, Type &object)
Binds a named ValueTree property to a data member of your object.
template<typename Type >
void addLambdaSet (const String &propertyName, std::function< Type() > saveToTree, std::function< void(Type &) > loadFromTree)
Binds lambda functions for saving and loading a certain value to and from a named ValueTree property.
void as (SerializableData &data)
Delegates another object to be serialized as this object's data.
ValueTree & getRawDataTree ()
Returns a reference to this reflector's root ValueTree.
virtual bool isLoading () const =0
Returns true if this reflector is loading state.
bool isSaving () const
Returns true if this reflector is saving state.
Detailed Description
Utility class that provides a convenient API for assigning data members or lambdas to ValueTree properties for use in serializing logic.
You should never have to create one of these; the SerializableData class will internally create and use TreeLoaders and TreeSavers when you call its top-level load and save functions.
Internally, this class uses the toVar() and fromVar() functions to encode various C++ types into ValueTree properties. Implement those two functions within the lemons::serializing namespace for any custom type you wish to easily serialize.
As a general rule, you shouldn't need to implement toVar() and fromVar() for a type if that type inherits from SerializableData; and, conversely, you should implement toVar() and fromVar() for a type if it needs to be serialized and doesn't inherit from SerializableData. You should rarely, if ever, need both for a single type.
See also
SerializableData, serializing::toVar(), serializing::fromVar()
Constructor & Destructor Documentation
TreeReflector()
lemons::TreeReflector::TreeReflector (const ValueTree & treeToUse) explicit
Creates a TreeReflector.
Whether this reflector is loading or saving, it must be given a ValueTree to reference.
~TreeReflector()
virtual lemons::TreeReflector::~TreeReflector () virtual default
Destructor.
Member Function Documentation
add()
template<typename Type > void lemons::TreeReflector::add (const String & propertyName, Type & object)
Binds a named ValueTree property to a data member of your object.
If the passed object is a ValueTree, it will be appended to this reflector's internal ValueTree using normal ValueTree methods.
If the passed object inherits from SerializableData, this will call serialize() on it and append the resulting ValueTree to the reflector's internal tree.
If the passed object is a container, this will create a subtree for the container and populate it by calling add() on each element of the container. This works recursively for multidimensional containers as well.
If the passed object is any other kind of C++ object, this will call serializing::toVar() to save the object to the ValueTree, or serializing::fromVar() to restore from the tree.
For example:
struct SomethingSerializable : lemons::SerializableData
{
    // we want to save this integer with our program's state
    int data;
    void serialize (TreeReflector& ref) final
    {
        // simply choose a property name -- and that's it!
        ref.add ("MyData", data);
    }
};
Attention
Be careful not to use duplicate property names in the serialization logic for a single object!
Example – what NOT to do:
struct SomethingSerializable : lemons::SerializableData
{
    int number;
    String string;
    void serialize (TreeReflector& ref) final
    {
        ref.add ("ThisWillBreak!", number);
        ref.add ("ThisWillBreak!", string);
    }
};
In the above example, the 'string' data will overwrite the 'number' data, because the programmer has chosen duplicate property names.
Container types you wish to serialize with a single call to add() must fulfill the following:
have begin() and end() functions – ie, are compatable with range-based for loops
have an implementation of serializing::ContainerInterface
have a specialization of serializing::getInterfaceForContainer()
have a specialization of serializing::isContainer that inherits std::true_type
The container's elements must themselves be valid calls to add() – ie, either inherit from SerializableData or have serializing::toVar() and serializing::fromVar() implemented.
Provided in Lemons are implementations for common STL containers and JUCE containers. You can implement the above requirements for this to work with any other custom type you create.
For example:
struct SomethingSerializable : lemons::SerializableData
{
    std::vector<int> data;
    void serialize (TreeReflector& ref) final
    {
        ref.add ("Ints", data);
    }
};
This will create a sub-tree in your object's ValueTree named "Ints", with properties "Int_1", "Int_2", "Int_3"... etc. This works by iterating through each element of your container and calling add() on each of them.
Parameters
propertyName The property name associated with the piece of data this function call represents.
When adding a reference to a member encoded with toVar() and fromVar(), this is the name of the ValueTree property the encoded object will be saved to and restored from in the reflector's internal ValueTree.
When adding a sub-tree object (such as when passing a child ValueTree, a child object that inherits from SerializableData, or a container), this is the name of the sub-tree that will be added to the reflector's internal tree, and will be populated with the child object's properties.
When adding a container, the container's individual element names are generated as following:
std::vector<int> data {23, 16, 7};
ref.add ("Points", data);
This will create the following sub-tree object:
    <Points>
        <Point_1 = 23>
        <Point_2 = 16>
        <Point_3 = 7>
I do not recommend attempting to internationalize property names.
Take care to avoid duplicating property names for multiple data members of the same serializable object!
object Reference to the data member you wish to load/save.
This can be:
Any C++ object for which toVar() and fromVar() are implemented;
A juce::ValueTree;
Another object that inherits from SerializableData;
A container that has serializing::ContainerInterface, serializing::getInterfaceForContainer(), and serializing::isContainer implemented and whose elements are also valid calls to add()
See also
serializing::ContainerInterface, serializing::getInterfaceForContainer(), serializing::isContainer, serializing::toVar(), serializing::fromVar(), addLambdaSet()
References isLoading().
addLambdaSet()
template<typename Type > void lemons::TreeReflector::addLambdaSet (const String & propertyName, std::function< Type() > saveToTree, std::function< void(Type &) > loadFromTree)
Binds lambda functions for saving and loading a certain value to and from a named ValueTree property.
This follows the same semantics as add(), but provides the ability to fetch the value using a lambda, and call a lambda with the value retrieved from the tree, instead of providing a reference to an object.
For example:
 struct SomethingSerializable : lemons::SerializableData
 {
    void setData (int newData)
    {
        data = newData;
        // do something else with side effects...
    }
private:
    // we still want to save this integer with our program's state, but I want to call setData() when it's being loaded...
    int data;
    void serialize (TreeReflector& ref) final
    {
        // you can specify lambdas for retrieving and saving a property's value as a specified type (int)
        ref.addLambdaSet<int> ("MyData",
                                [&]{ return data; },
                                [&](int& newData){ setData (newData); });
    }
 };
If you use this function with a container type, your lambdas must return/recieve the entire container by value. I recommend sticking to add() (or implementing completely custom logic) for containers.
Parameters
propertyName The name of the ValueTree property that this data corresponds to. See the docs for add().
saveToTree This lambda should return the current value of the data you wish to save.
loadFromTree This lambda will be called with the new value for this data when a new state is loaded.
See also
add(), serializing::toVar(), serializing::fromVar()
References isLoading().
as()
void lemons::TreeReflector::as (SerializableData & data)
Delegates another object to be serialized as this object's data.
The use case for this is if you're implementing a wrapper type that adds functionality to another serializable type, but has no stateful data of its own, and you want to serialize the state data without it being in a subtree of your object's node in the parent tree.
For example, say you've got the following types:
using namespace lemons;
struct StateData : SerializableData
{
    int x {12}, y {48};
    void serialize (TreeReflector& ref) final
    {
        ref.add ("X", x);
        ref.add ("Y", y);
    }
};
struct Wrapper : SerializableData
{
    StateData data;
    // add some more functionality to "data"...
};
How would you write Wrapper's serialize() function?
You could do this:
struct Wrapper : SerializableData
{
    StateData data;
    void serialize (TreeReflector& ref) final
    {
        ref.add ("Data", data);
    }
};
The above code will produce the following tree when Wrapper is serialized:
<Wrapper>
    <Data>
        <X = 12>
        <Y = 48>
But, if you do this:
struct Wrapper : SerializableData
{
    StateData data;
    void serialize (TreeReflector& ref) final
    {
        ref.as (data);
    }
};
Then you'll get this tree:
<Wrapper>
    <X = 12>
    <Y = 48>
See the plugin::ParameterHolder class for an example of when this is useful.
Attention
If you use as() in your object's serializing logic, then it should be the only line of code in your serializing function!
getRawDataTree()
ValueTree& lemons::TreeReflector::getRawDataTree ()
Returns a reference to this reflector's root ValueTree.
Attention
Handle with care! The tree this function returns may already contain sub-nodes representing other serialized children of whatever object is serializing you at the moment...
isLoading()
virtual bool lemons::TreeReflector::isLoading () const pure virtual
Returns true if this reflector is loading state.
Implemented in lemons::TreeSaver, and lemons::TreeLoader.
Referenced by add(), and addLambdaSet().
isSaving()
bool lemons::TreeReflector::isSaving () const
Returns true if this reflector is saving state.
The documentation for this struct was generated from the following files:
TreeReflector.h
detail.h