Lemons: lemons::dsp::AudioFile Struct Reference
lemons::dsp::AudioFile Struct Reference final
Audio » lemons_dsp » Audio files
This class represents the data of an audio file, including the AudioBuffer itself, as well as the samplerate, bit depth, and metadata information.
Public Member Functions
AudioFile ()=default
Creates an invalid audio file.
AudioFile (AudioFile &&other) noexcept
AudioFile (const AudioFile &other) noexcept
AudioFile (const File &audioFile)
Creates an AudioFile from a file on disk.
AudioFile (std::unique_ptr< juce::InputStream > audioStream)
Creates an AudioFile from any kind of input stream.
bool duplicateIfShared ()
bool existsOnDisk () const noexcept
Returns true if the file this data represents exists locally on the current device.
juce::AudioFormat * getAudioFormat () const
Returns the audio format object for this file's audio format.
int getBitsPerSample () const noexcept
Returns the number of bits per sample in this audio file.
template<typename SampleType >
const AudioBuffer< SampleType > & getData ()
Returns the actual audio data of this audio file.
File getFile () const noexcept
Returns the File object that this audio file was loaded from.
String getFormatName () const noexcept
Returns the name of the audio format, eg, 'wav' or 'aiff'.
double getLengthInSeconds () const noexcept
Returns the length in seconds of the entire audio file at its original samplerate.
const juce::StringPairArray & getMetadata () const noexcept
Returns the audio file's metadata values.
int getNumChannels () const noexcept
Returns the number of channels in the audio file.
int getNumSamples () const noexcept
Returns the number of samples in the audio file.
int getReferenceCount () const noexcept
double getSamplerate () const noexcept
Returns the samplerate of the audio file.
bool isValid () const noexcept
Returns true if the file's data was loaded successfully.
Detailed Description
This class represents the data of an audio file, including the AudioBuffer itself, as well as the samplerate, bit depth, and metadata information.
One of these can be created from an audio file on disk, or from any kind of juce::InputStream.
Constructor & Destructor Documentation
AudioFile() [1/5]
lemons::dsp::AudioFile::AudioFile () default
Creates an invalid audio file.
AudioFile() [2/5]
lemons::dsp::AudioFile::AudioFile (const File & audioFile) explicit
Creates an AudioFile from a file on disk.
AudioFile() [3/5]
lemons::dsp::AudioFile::AudioFile (std::unique_ptr< juce::InputStream > audioStream) explicit
Creates an AudioFile from any kind of input stream.
AudioFile() [4/5]
lemons::dsp::AudioFile::AudioFile (const AudioFile & other) noexcept
AudioFile() [5/5]
lemons::dsp::AudioFile::AudioFile (AudioFile && other) noexcept
Member Function Documentation
duplicateIfShared()
bool lemons::dsp::AudioFile::duplicateIfShared ()
References getData(), getLengthInSeconds(), and isValid().
existsOnDisk()
bool lemons::dsp::AudioFile::existsOnDisk () const noexcept
Returns true if the file this data represents exists locally on the current device.
This may return false if the file has been deleted since the construction of this object, or if you used the constructor that takes an input stream.
getAudioFormat()
juce::AudioFormat * lemons::dsp::AudioFile::getAudioFormat () const
Returns the audio format object for this file's audio format.
getBitsPerSample()
int lemons::dsp::AudioFile::getBitsPerSample () const noexcept
Returns the number of bits per sample in this audio file.
getData()
template<typename SampleType > const AudioBuffer< SampleType > & lemons::dsp::AudioFile::getData ()
Returns the actual audio data of this audio file.
If isValid() returns false, then this function will return a buffer with a size of 0 channels and 0 samples. Internally, the data is always loaded as floats; the first time you call the double version of this function, the data will be converted to double precision internally.
Referenced by duplicateIfShared().
getFile()
File lemons::dsp::AudioFile::getFile () const noexcept
Returns the File object that this audio file was loaded from.
Note that this may return an invalid File object if you used the constructor that takes an input stream.
getFormatName()
String lemons::dsp::AudioFile::getFormatName () const noexcept
Returns the name of the audio format, eg, 'wav' or 'aiff'.
getLengthInSeconds()
double lemons::dsp::AudioFile::getLengthInSeconds () const noexcept
Returns the length in seconds of the entire audio file at its original samplerate.
Referenced by duplicateIfShared().
getMetadata()
const juce::StringPairArray & lemons::dsp::AudioFile::getMetadata () const noexcept
Returns the audio file's metadata values.
getNumChannels()
int lemons::dsp::AudioFile::getNumChannels () const noexcept
Returns the number of channels in the audio file.
getNumSamples()
int lemons::dsp::AudioFile::getNumSamples () const noexcept
Returns the number of samples in the audio file.
getReferenceCount()
int lemons::dsp::AudioFile::getReferenceCount () const noexcept
getSamplerate()
double lemons::dsp::AudioFile::getSamplerate () const noexcept
Returns the samplerate of the audio file.
isValid()
bool lemons::dsp::AudioFile::isValid () const noexcept
Returns true if the file's data was loaded successfully.
Referenced by duplicateIfShared().
The documentation for this struct was generated from the following file:
AudioFile.h