Lemons: lemons::plugin::TypedProcessorHolder< ProcessorType, > Struct Template Reference
lemons::plugin::TypedProcessorHolder< ProcessorType, > Struct Template Reference final
Plugins » lemons_plugin_hosting » ProcessorHolder
A ProcessorHolder that instantiates a custom subclass of AudioProcessor and automatically creates a ProcessorHolder for you.
Public Types
using ParameterState = juce::Array< ParameterStateData >
A simple representation of a processor's state.
Public Member Functions
TypedProcessorHolder ()
Constructor.
juce::AudioProcessorParameter * getNamedParameter (const String &name)
Finds a parameter with a specified name.
const juce::AudioProcessorParameter * getNamedParameter (const String &name) const
Finds a parameter with a specified name.
ParameterState getStateOfParameters () const
Returns the current state of the processor's parameters.
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) >
ParameterType * getTypedParameter (const String &name)
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) >
const ParameterType * getTypedParameter (const String &name) const
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
juce::AudioProcessor * operator-> ()
Returns a pointer to the managed AudioProcessor.
const juce::AudioProcessor * operator-> () const
Returns a pointer to the managed AudioProcessor.
template<typename SampleType >
bool prepareForPlayback (double samplerate, int blocksize, int numChannels=2)
Prepares the processor for playback.
void setStateOfParameters (const ParameterState &state)
Restores a previous parameter state.
Public Attributes
juce::AudioProcessor & processor
The managed audio processor.
ProcessorType typedProcessor
The managed processor.
Detailed Description
template<typename ProcessorType, LEMONS_MUST_INHERIT_FROM(ProcessorType, juce::AudioProcessor)>
struct lemons::plugin::TypedProcessorHolder< ProcessorType, >
A ProcessorHolder that instantiates a custom subclass of AudioProcessor and automatically creates a ProcessorHolder for you.
Template Parameters
ProcessorType The type of processor you wish to instantiate. This type must inherit from juce::AudioProcessor.
See also
ProcessorHolder
Member Typedef Documentation
ParameterState
using lemons::plugin::ProcessorHolder::ParameterState = juce::Array<ParameterStateData> inherited
A simple representation of a processor's state.
Constructor & Destructor Documentation
TypedProcessorHolder()
template<typename ProcessorType , LEMONS_MUST_INHERIT_FROM(ProcessorType, juce::AudioProcessor) > lemons::plugin::TypedProcessorHolder< ProcessorType, >::TypedProcessorHolder ()
Constructor.
Member Function Documentation
getNamedParameter() [1/2]
juce::AudioProcessorParameter* lemons::plugin::ProcessorHolder::getNamedParameter (const String & name) inherited
Finds a parameter with a specified name.
Referenced by lemons::plugin::ProcessorHolder::getTypedParameter().
getNamedParameter() [2/2]
const juce::AudioProcessorParameter* lemons::plugin::ProcessorHolder::getNamedParameter (const String & name) const inherited
Finds a parameter with a specified name.
getStateOfParameters()
ParameterState lemons::plugin::ProcessorHolder::getStateOfParameters () const inherited
Returns the current state of the processor's parameters.
getTypedParameter() [1/2]
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) > ParameterType* lemons::plugin::ProcessorHolder::getTypedParameter (const String & name) inherited
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
Template Parameters
ParameterType The type of parameter class you want to access the parameter as. This type must inherit from juce::AudioProcessorParameter.
References lemons::plugin::ProcessorHolder::getNamedParameter().
getTypedParameter() [2/2]
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) > const ParameterType* lemons::plugin::ProcessorHolder::getTypedParameter (const String & name) const inherited
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
Template Parameters
ParameterType The type of parameter class you want to access the parameter as. This type must inherit from juce::AudioProcessorParameter.
References lemons::plugin::ProcessorHolder::getNamedParameter().
operator->() [1/2]
juce::AudioProcessor* lemons::plugin::ProcessorHolder::operator-> () inherited
Returns a pointer to the managed AudioProcessor.
operator->() [2/2]
const juce::AudioProcessor* lemons::plugin::ProcessorHolder::operator-> () const inherited
Returns a pointer to the managed AudioProcessor.
prepareForPlayback()
template<typename SampleType > bool lemons::plugin::ProcessorHolder::prepareForPlayback (double samplerate, int blocksize, int numChannels = 2) inherited
Prepares the processor for playback.
Internally, this sets the appropriate processing precision and buses layout and calls prepareToPlay().
setStateOfParameters()
void lemons::plugin::ProcessorHolder::setStateOfParameters (const ParameterState & state) inherited
Restores a previous parameter state.
Member Data Documentation
processor
juce::AudioProcessor& lemons::plugin::ProcessorHolder::processor inherited
The managed audio processor.
typedProcessor
template<typename ProcessorType , LEMONS_MUST_INHERIT_FROM(ProcessorType, juce::AudioProcessor) > ProcessorType lemons::plugin::TypedProcessorHolder< ProcessorType, >::typedProcessor
The managed processor.
The documentation for this struct was generated from the following file:
ProcessorHolder.h