Lemons: lemons::TreeSaver Struct Reference
lemons::TreeSaver Struct Reference
Public Member Functions
bool isLoading () const final
TreeReflector (const ValueTree &treeToUse)
bool isSaving () const
ValueTree & getRawDataTree ()
template<typename Type >
void add (const String &propertyName, Type &object)
Member Function Documentation
isLoading()
bool lemons::TreeSaver::isLoading () const final virtual
Implements lemons::TreeReflector.
TreeReflector()
lemons::TreeReflector::TreeReflector explicit
isSaving()
bool lemons::TreeReflector::isSaving () const inherited
getRawDataTree()
ValueTree& lemons::TreeReflector::getRawDataTree () inherited
Referenced by lemons::TreeReflectorHelpers::addContainer().
add()
template<typename Type > void lemons::TreeReflector::add (const String & propertyName, Type & object) inherited
References lemons::TreeReflector::isLoading().
Referenced by lemons::TreeReflectorHelpers::addContainer().
The documentation for this struct was generated from the following file:
TreeReflector.h