Lemons: lemons::plugin::ProcessorHolder Struct Reference
lemons::plugin::ProcessorHolder Struct Reference
Plugins » lemons_plugin » Plugin hosting
This class holds a reference to a juce::AudioProcessor, and acts as a wrapper around it, providing some convenience and utility functions.
Classes
struct ParameterStateData
A simple representation of a parameter's state.
Public Types
using ParameterState = juce::Array< ParameterStateData >
A simple representation of a processor's state.
Public Member Functions
ProcessorHolder (juce::AudioProcessor &processorToUse)
Creates a ProcessorHolder that manages the specified AudioProcessor.
virtual ~ProcessorHolder ()=default
Destructor.
ParameterState getStateOfParameters () const
Returns the current state of the processor's parameters.
juce::AudioProcessor * operator-> ()
Returns a pointer to the managed AudioProcessor.
const juce::AudioProcessor * operator-> () const
Returns a pointer to the managed AudioProcessor.
template<typename SampleType >
bool prepareForPlayback (double samplerate, int blocksize, int numChannels=2)
Prepares the processor for playback.
void setStateOfParameters (const ParameterState &state)
Restores a previous parameter state.
processor_holder_access_params Accessing parameters
juce::AudioProcessorParameter * getNamedParameter (const String &name)
Finds a parameter with a specified name.
const juce::AudioProcessorParameter * getNamedParameter (const String &name) const
Finds a parameter with a specified name.
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) >
ParameterType * getTypedParameter (const String &name)
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) >
const ParameterType * getTypedParameter (const String &name) const
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
Public Attributes
juce::AudioProcessor & processor
The managed audio processor.
Detailed Description
This class holds a reference to a juce::AudioProcessor, and acts as a wrapper around it, providing some convenience and utility functions.
To instantiate a custom subclass of AudioProcessor and pass it into one of these automatically, use the TypedProcessorHolder class.
See also
TypedProcessorHolder
Member Typedef Documentation
ParameterState
using lemons::plugin::ProcessorHolder::ParameterState = juce::Array<ParameterStateData>
A simple representation of a processor's state.
Constructor & Destructor Documentation
ProcessorHolder()
lemons::plugin::ProcessorHolder::ProcessorHolder (juce::AudioProcessor & processorToUse) explicit
Creates a ProcessorHolder that manages the specified AudioProcessor.
~ProcessorHolder()
virtual lemons::plugin::ProcessorHolder::~ProcessorHolder () virtual default
Destructor.
Member Function Documentation
getNamedParameter() [1/2]
juce::AudioProcessorParameter * lemons::plugin::ProcessorHolder::getNamedParameter (const String & name)
Finds a parameter with a specified name.
Referenced by getTypedParameter().
getNamedParameter() [2/2]
const juce::AudioProcessorParameter * lemons::plugin::ProcessorHolder::getNamedParameter (const String & name) const
Finds a parameter with a specified name.
getStateOfParameters()
ParameterState lemons::plugin::ProcessorHolder::getStateOfParameters () const
Returns the current state of the processor's parameters.
getTypedParameter() [1/2]
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) > ParameterType * lemons::plugin::ProcessorHolder::getTypedParameter (const String & name)
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
Template Parameters
ParameterType The type of parameter class you want to access the parameter as. This type must inherit from juce::AudioProcessorParameter.
References getNamedParameter().
getTypedParameter() [2/2]
template<typename ParameterType , LEMONS_MUST_INHERIT_FROM(ParameterType, juce::AudioProcessorParameter) > const ParameterType * lemons::plugin::ProcessorHolder::getTypedParameter (const String & name) const
Finds a parameter with a specified name, and attempts to cast it to the specified subclass of juce::AudioProcessorParameter.
Template Parameters
ParameterType The type of parameter class you want to access the parameter as. This type must inherit from juce::AudioProcessorParameter.
References getNamedParameter().
operator->() [1/2]
juce::AudioProcessor * lemons::plugin::ProcessorHolder::operator-> ()
Returns a pointer to the managed AudioProcessor.
operator->() [2/2]
const juce::AudioProcessor * lemons::plugin::ProcessorHolder::operator-> () const
Returns a pointer to the managed AudioProcessor.
prepareForPlayback()
template<typename SampleType > bool lemons::plugin::ProcessorHolder::prepareForPlayback (double samplerate, int blocksize, int numChannels = 2)
Prepares the processor for playback.
Internally, this sets the appropriate processing precision and buses layout and calls prepareToPlay().
setStateOfParameters()
void lemons::plugin::ProcessorHolder::setStateOfParameters (const ParameterState & state)
Restores a previous parameter state.
Member Data Documentation
processor
juce::AudioProcessor& lemons::plugin::ProcessorHolder::processor
The managed audio processor.
The documentation for this struct was generated from the following file:
ProcessorHolder.h