Lemons: lemons::plugin::LFO Struct Reference
lemons::plugin::LFO Struct Reference final abstract
Public Types
using Osc = dsp::osc::ChoosableOscillator< float >
Internally, LFOs use ChoosableOscillator to generate their values.
using ParameterValueType = float
The parameter's value type is publically accessible through this typedef.
Public Member Functions
LFO (const ParameterList &parameterListToUse, const String &paramName)
void applyAllConnections () const
Applies the meta parameter's current value to all of its connections.
void createOrEditConnection (Parameter &parameter, float minAmt, float maxAmt)
Creates or edits a connection to a given parameter.
void finishBlock (int numSamples)
float get () const noexcept
Returns the parameter's current value.
float getCurrentOscillatorValue () const noexcept
float getDefault () const noexcept
Returns the parameter's current default value.
float getDenormalizedValue () const noexcept
Returns the parameter's current value, in the parameter's denormalized range.
float getMaximum () const noexcept
Returns the maximum possible value for this parameter.
float getMinimum () const noexcept
Returns the minimum possible value for this parameter.
const ParameterRange & getNormalisableRange () const final
Returns this parameter's range object.
float getNormalizedValue () const noexcept
Returns the parameter's current value, in a normalized 0-1 range.
Osc & getOscillator () noexcept
Returns a reference to the LFO's internal ChoosableOscillator object.
virtual const Parameter & getParameter () const =0
Returns the actual parameter object that is controlling this meta parameter – ie, the parameter that is sending out its values to control the others.
ParameterTraits getParameterTraits () const final
Returns a ParameterTraits object representing this parameter.
String getStringForCurrentValue (int maxLength=50) const
Returns a textual description of the parameter's current value.
String getStringForValue (float value, int maxLength=50) const
Returns a textual description for a parameter value.
float getValueForString (const String &string) const
Converts some user input text to a possible representation as a parameter value.
bool hasConnection (const Parameter &parameter) const
Returns true if this meta parameter is currently connected to the given parameter.
bool isAutomatable () const final
Returns true if this parameter is automatable by the user's DAW.
bool isMetaParameter () const final
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
void loadConnectionsFromValueTree (const ValueTree &tree)
Recreates the state of a saved set of connections.
void loadFromValueTree (const ValueTree &tree) final
Restores the parameter's state from a ValueTree.
void prepareToPlay (int numSamples, double samplerate)
Prepares the LFO for processing.
bool removeConnection (const Parameter &parameter)
Removes the connection to the given parameter, if any.
ValueTree saveConnectionsToValueTree () const
Saves the state of this meta parameter's connections to a ValueTree.
ValueTree saveToValueTree () const final
Saves the state of this parameter to a ValueTree.
ValueTree saveToValueTree () const override
Saves the state of this meta parameter to a ValueTree.
void set (float newValue)
Sets the parameter's value.
void setDefault (float newDefault)
Sets the parameter's default value.
void setDenormalizedValue (float value)
Sets the parameter's value, in the parameter's denormalized range.
void setNormalizedValue (float value)
Sets the parameter's value, in a normalized 0-1 range.
Static Public Attributes
static constexpr auto id_prop = "id"
static constexpr auto valueTreeType = "Connections"
Protected Member Functions
float denormalize (float input) const noexcept
Denormalizes the passed value using the parameter's NormalisableRange object.
float normalize (float input) const noexcept
Normalizes the passed value using the parameter's NormalisableRange object.
Static Protected Attributes
static constexpr auto controller_prop = "controllerNumber"
static constexpr auto default_prop = "default"
static constexpr auto value_prop = "value"
static constexpr auto valueTreeType = "PARAM"
Detailed Description
An LFO, to be used by a ModulationManager object. Internally, this class uses a dsp::osc::ChoosableOscillator to generate its values.
Member Typedef Documentation
Osc
using lemons::plugin::LFO::Osc = dsp::osc::ChoosableOscillator<float>
Internally, LFOs use ChoosableOscillator to generate their values.
ParameterValueType
using lemons::plugin::TypedParameter< float >::ParameterValueType = float inherited
The parameter's value type is publically accessible through this typedef.
Constructor & Destructor Documentation
LFO()
lemons::plugin::LFO::LFO (const ParameterList & parameterListToUse, const String & paramName) explicit
Member Function Documentation
applyAllConnections()
void lemons::plugin::MetaParameterBase::applyAllConnections () const inherited
Applies the meta parameter's current value to all of its connections.
beginGesture()
void lemons::plugin::Parameter::beginGesture () inherited
Begins a change gesture for this parameter.
createOrEditConnection()
void lemons::plugin::MetaParameterBase::createOrEditConnection (Parameter & parameter, float minAmt, float maxAmt) inherited
Creates or edits a connection to a given parameter.
If a connection to the given parameter already exists, it will be remapped to the new min & max amounts; otherwise, a new connection will be created. The min and max values should be between 0.f and 1.f, and can be thought of as the percent effect this meta parameter will have on this parameter.
denormalize()
float lemons::plugin::Parameter::denormalize (float input) const protected noexcept inherited
Denormalizes the passed value using the parameter's NormalisableRange object.
Referenced by lemons::plugin::Parameter::getDenormalizedDefault(), and lemons::plugin::Parameter::getDenormalizedValue().
endGesture()
void lemons::plugin::Parameter::endGesture () inherited
Ends any active change gesture for this parameter.
finishBlock()
void lemons::plugin::LFO::finishBlock (int numSamples)
get()
float lemons::plugin::TypedParameter< float >::get () const noexcept inherited
Returns the parameter's current value.
getCurrentOscillatorValue()
float lemons::plugin::LFO::getCurrentOscillatorValue () const noexcept
getDefault()
float lemons::plugin::TypedParameter< float >::getDefault () const noexcept inherited
Returns the parameter's current default value.
getDenormalizedDefault()
float lemons::plugin::Parameter::getDenormalizedDefault () const noexcept inherited
Returns the parameter's default value, in the parameter's denormalized range.
See also
getNormalizedDefault()
References lemons::plugin::Parameter::denormalize(), and lemons::plugin::Parameter::getNormalizedDefault().
getDenormalizedValue()
float lemons::plugin::Parameter::getDenormalizedValue () const noexcept inherited
Returns the parameter's current value, in the parameter's denormalized range.
See also
getNormalizedValue()
References lemons::plugin::Parameter::denormalize().
getMaximum()
float lemons::plugin::TypedParameter< float >::getMaximum () const noexcept inherited
Returns the maximum possible value for this parameter.
getMidiControllerNumber()
int lemons::plugin::Parameter::getMidiControllerNumber () const noexcept inherited
Returns the number of the MIDI controller mapped to this parameter, or -1 if this parameter is unmapped.
getMinimum()
float lemons::plugin::TypedParameter< float >::getMinimum () const noexcept inherited
Returns the minimum possible value for this parameter.
getNormalisableRange()
const ParameterRange& lemons::plugin::Parameter::getNormalisableRange () const final inherited
Returns this parameter's range object.
getNormalizedDefault()
float lemons::plugin::Parameter::getNormalizedDefault () const noexcept inherited
Returns the parameter's default value, in a normalized 0-1 range.
See also
getDenormalizedDefault()
Referenced by lemons::plugin::Parameter::getDenormalizedDefault(), lemons::plugin::Parameter::refreshDefault(), and lemons::plugin::Parameter::resetToDefault().
getNormalizedValue()
float lemons::plugin::Parameter::getNormalizedValue () const noexcept inherited
Returns the parameter's current value, in a normalized 0-1 range.
See also
getDenormalizedValue()
getOscillator()
Osc& lemons::plugin::LFO::getOscillator () noexcept
Returns a reference to the LFO's internal ChoosableOscillator object.
You can then call methods on the oscillator to, for example, set its frequency, change the type, etc.
getParameter()
virtual const Parameter& lemons::plugin::MetaParameterBase::getParameter () const pure virtual inherited
Returns the actual parameter object that is controlling this meta parameter – ie, the parameter that is sending out its values to control the others.
getParameterTraits() [1/2]
virtual ParameterTraits lemons::plugin::Parameter::getParameterTraits () const virtual inherited
Returns a ParameterTraits object representing this parameter.
An object identical to this one can be recreated using the constructor that takes a ParameterTraits object.
Reimplemented in lemons::plugin::TypedParameter< ValueType >.
getParameterTraits() [2/2]
ParameterTraits lemons::plugin::TypedParameter< float >::getParameterTraits () const final inherited
Returns a ParameterTraits object representing this parameter.
getStringForCurrentValue()
String lemons::plugin::TypedParameter< float >::getStringForCurrentValue (int maxLength = 50) const inherited
Returns a textual description of the parameter's current value.
getStringForValue()
String lemons::plugin::TypedParameter< float >::getStringForValue (ValueType value, int maxLength = 50) const inherited
Returns a textual description for a parameter value.
getTextForCurrentValue()
String lemons::plugin::Parameter::getTextForCurrentValue () const inherited
Returns a textual representation of the parameter's current value.
getTextForDenormalizedValue()
String lemons::plugin::Parameter::getTextForDenormalizedValue (float value) const inherited
Returns a textual description of a value in the parameter's denormalized range.
See also
getTextForNormalizedValue()
References lemons::plugin::Parameter::getTextForNormalizedValue(), and lemons::plugin::Parameter::normalize().
Referenced by lemons::plugin::Parameter::getTextForMax(), and lemons::plugin::Parameter::getTextForMin().
getTextForMax()
String lemons::plugin::Parameter::getTextForMax () const inherited
Returns a textual description of the parameter's maximum value.
See also
getTextForMin()
References lemons::plugin::Parameter::getTextForDenormalizedValue().
getTextForMin()
String lemons::plugin::Parameter::getTextForMin () const inherited
Returns a textual description of the parameter's minimum value.
See also
getTextForMax()
References lemons::plugin::Parameter::getTextForDenormalizedValue().
getTextForNormalizedValue()
String lemons::plugin::Parameter::getTextForNormalizedValue (float value) const inherited
Returns a textual description of a normalized value in the range 0-1.
See also
getTextForDenormalizedValue()
Referenced by lemons::plugin::Parameter::getTextForDenormalizedValue().
getValueForString()
float lemons::plugin::TypedParameter< float >::getValueForString (const String & string) const inherited
Converts some user input text to a possible representation as a parameter value.
hasConnection()
bool lemons::plugin::MetaParameterBase::hasConnection (const Parameter & parameter) const inherited
Returns true if this meta parameter is currently connected to the given parameter.
isAutomatable()
bool lemons::plugin::Parameter::isAutomatable () const final inherited
Returns true if this parameter is automatable by the user's DAW.
isChanging()
bool lemons::plugin::Parameter::isChanging () const noexcept inherited
Returns true if this parameter is currently in the middle of a change gesture.
isMetaParameter()
bool lemons::plugin::Parameter::isMetaParameter () const final inherited
Returns true if this parameter is a "meta parameter", ie, one that controls the values of other parameters.
isMidiControllerMapped()
bool lemons::plugin::Parameter::isMidiControllerMapped () const noexcept inherited
Returns true if this parameter is currently mapped to a MIDI controller.
loadConnectionsFromValueTree()
void lemons::plugin::MetaParameterBase::loadConnectionsFromValueTree (const ValueTree & tree) inherited
Recreates the state of a saved set of connections.
See also
saveConnectionsToValueTree()
loadFromValueTree()
void lemons::plugin::LFO::loadFromValueTree (const ValueTree & tree) final virtual
Restores the parameter's state from a ValueTree.
Reimplemented from lemons::plugin::TypedParameter< float >.
normalize()
float lemons::plugin::Parameter::normalize (float input) const protected noexcept inherited
Normalizes the passed value using the parameter's NormalisableRange object.
Referenced by lemons::plugin::Parameter::getTextForDenormalizedValue(), lemons::plugin::Parameter::setDenormalizedDefault(), and lemons::plugin::Parameter::setDenormalizedValue().
prepareToPlay()
void lemons::plugin::LFO::prepareToPlay (int numSamples, double samplerate)
Prepares the LFO for processing.
processNewControllerMessage()
bool lemons::plugin::Parameter::processNewControllerMessage (int controllerNumber, int controllerValue) inherited
Call this function with each MIDI CC message your plugin recieves, and the Parameter class will automatically update itself with changes in the appropriate controller, if a mapping is active.
Returns
True if this parameter is mapped to the passed controller number.
refreshDefault()
void lemons::plugin::Parameter::refreshDefault () inherited
Sets the parameter's current value as the default value.
References lemons::plugin::Parameter::getNormalizedDefault(), and lemons::plugin::Parameter::setNormalizedDefault().
removeConnection()
bool lemons::plugin::MetaParameterBase::removeConnection (const Parameter & parameter) inherited
Removes the connection to the given parameter, if any.
Returns
True if a connection previously existed to the given parameter
removeMidiControllerMapping()
void lemons::plugin::Parameter::removeMidiControllerMapping () noexcept inherited
Removes the MIDI controller mapping, if any.
References lemons::plugin::Parameter::setMidiControllerNumber().
resetToDefault()
void lemons::plugin::Parameter::resetToDefault () inherited
Resets the parameter to the saved default value.
References lemons::plugin::Parameter::getNormalizedDefault(), and lemons::plugin::Parameter::setNormalizedValue().
saveConnectionsToValueTree()
ValueTree lemons::plugin::MetaParameterBase::saveConnectionsToValueTree () const inherited
Saves the state of this meta parameter's connections to a ValueTree.
See also
loadConnectionsFromValueTree()
saveToValueTree() [1/2]
ValueTree lemons::plugin::LFO::saveToValueTree () const final virtual
Saves the state of this parameter to a ValueTree.
Reimplemented from lemons::plugin::Parameter.
saveToValueTree() [2/2]
ValueTree lemons::plugin::MetaParameter< float >::saveToValueTree override virtual inherited
Saves the state of this meta parameter to a ValueTree.
Reimplemented from lemons::plugin::TypedParameter< float >.
set()
void lemons::plugin::TypedParameter< float >::set (ValueType newValue) inherited
Sets the parameter's value.
setDefault()
void lemons::plugin::TypedParameter< float >::setDefault (ValueType newDefault) inherited
Sets the parameter's default value.
setDenormalizedDefault()
void lemons::plugin::Parameter::setDenormalizedDefault (float value) inherited
Sets the parameter's default, in the parameter's denormalized range.
See also
setNormalizedDefault()
References lemons::plugin::Parameter::normalize(), and lemons::plugin::Parameter::setNormalizedDefault().
setDenormalizedValue()
void lemons::plugin::Parameter::setDenormalizedValue (float value) inherited
Sets the parameter's value, in the parameter's denormalized range.
See also
setNormalizedValue()
References lemons::plugin::Parameter::normalize(), and lemons::plugin::Parameter::setNormalizedValue().
setMidiControllerNumber()
void lemons::plugin::Parameter::setMidiControllerNumber (int newControllerNumber) inherited
Maps this parameter to listen for changes in a specified MIDI controller number.
Referenced by lemons::plugin::Parameter::removeMidiControllerMapping().
setNormalizedDefault()
void lemons::plugin::Parameter::setNormalizedDefault (float value) inherited
Sets the parameter's default, in a normalized 0-1 range.
See also
setDenormalizedDefault()
Referenced by lemons::plugin::Parameter::refreshDefault(), and lemons::plugin::Parameter::setDenormalizedDefault().
setNormalizedValue()
void lemons::plugin::Parameter::setNormalizedValue (float value) inherited
Sets the parameter's value, in a normalized 0-1 range.
See also
setDenormalizedValue()
Referenced by lemons::plugin::Parameter::resetToDefault(), and lemons::plugin::Parameter::setDenormalizedValue().
Member Data Documentation
controller_prop
constexpr auto lemons::plugin::Parameter::controller_prop = "controllerNumber" static protected inherited
default_prop
constexpr auto lemons::plugin::Parameter::default_prop = "default" static protected inherited
id_prop
constexpr auto lemons::plugin::Parameter::id_prop = "id" static constexpr inherited
value_prop
constexpr auto lemons::plugin::Parameter::value_prop = "value" static protected inherited
valueTreeType [1/2]
constexpr auto lemons::plugin::MetaParameterBase::valueTreeType = "Connections" static constexpr inherited
valueTreeType [2/2]
constexpr auto lemons::plugin::Parameter::valueTreeType = "PARAM" static constexpr protected inherited
The documentation for this struct was generated from the following file:
LFO.h