Lemons: lemons::plugin::PluginState< StateType, > Struct Template Reference
lemons::plugin::PluginState< StateType, > Struct Template Reference
Plugins » lemons_plugin » state
Represents the top-level state of a plugin as a whole.
Public Member Functions
PluginState ()
Creates a new plugin state.
void deserialize (const ValueTree &tree)
Restores a previously saved state.
ValueTree serialize ()
Serializes the state of this object and returns a ValueTree.
Public Attributes
StateType state
The plugin's main state object.
StateToggles toggles {state}
The plugin's A/B/C state toggler.
UndoManager undo {state}
The plugin's undo manager.
Detailed Description
template<typename StateType, LEMONS_MUST_INHERIT_FROM(StateType, StateBase)>
struct lemons::plugin::PluginState< StateType, >
Represents the top-level state of a plugin as a whole.
This encapsulates your StateBase, State, or CustomState object along with a StateToggler and an UndoManager.
If you use my Processor class, it will instantiate one of these objects with the state type you passed to the processor class's template.
Template Parameters
StateType The type of state object to use to represent the plugin's state. This type must inherit from StateBase.
See also
Processor, StateBase, StateToggler, UndoManager
Constructor & Destructor Documentation
PluginState()
template<typename StateType , LEMONS_MUST_INHERIT_FROM(StateType, StateBase) > lemons::plugin::PluginState< StateType, >::PluginState ()
Creates a new plugin state.
Member Function Documentation
deserialize()
void lemons::SerializableData::deserialize (const ValueTree & tree) inherited
Restores a previously saved state.
Internally, this will create a TreeLoader object and call the virtual serialize(TreeReflector&) function.
Parameters
tree The saved state you wish to restore. This should usually be a ValueTree you got from a previous call to serialize().
If the state is incomplete, for a different kind of object, or otherwise corrupted, this function will only change the properties that it can successfully parse from the passed state. For example, if your serializable object uses properties named "apple", "orange", and "grape", and you pass a ValueTree with entries for "apple", "grapefruit", and "mango", then the "grapefruit" and "mango" properties will be ignored, and only the "apple" property will actually be loaded.
See also
TreeLoader, TreeReflector
serialize()
ValueTree lemons::SerializableData::serialize () inherited
Serializes the state of this object and returns a ValueTree.
Internally, this will create a TreeSaver object and call the virtual serialize(TreeReflector&) function.
See also
TreeSaver, TreeReflector
Member Data Documentation
state
template<typename StateType , LEMONS_MUST_INHERIT_FROM(StateType, StateBase) > StateType lemons::plugin::PluginState< StateType, >::state
The plugin's main state object.
Referenced by lemons::plugin::Processor< StateType, EngineType,, >::getState(), and lemons::plugin::PluginState< StateType >::PluginState().
toggles
template<typename StateType , LEMONS_MUST_INHERIT_FROM(StateType, StateBase) > StateToggles lemons::plugin::PluginState< StateType, >::toggles {state}
The plugin's A/B/C state toggler.
By default, it has 3 state slots.
Referenced by lemons::plugin::PluginState< StateType >::PluginState().
undo
template<typename StateType , LEMONS_MUST_INHERIT_FROM(StateType, StateBase) > UndoManager lemons::plugin::PluginState< StateType, >::undo {state}
The plugin's undo manager.
Referenced by lemons::plugin::PluginState< StateType >::PluginState().
The documentation for this struct was generated from the following file:
PluginState.h