include_guard (GLOBAL)

cmake_minimum_required (VERSION 3.22 FATAL_ERROR)

include (LemonsDefaultPlatformSettings)

option (LEMONS_ENABLE_INTEGRATIONS "Enable all available integrations by default" ON)

if (LEMONS_ENABLE_INTEGRATIONS)
	include (LemonsAllIntegrations)
endif()

set_property (GLOBAL PROPERTY REPORT_UNDEFINED_PROPERTIES "${PROJECT_SOURCE_DIR}/logs/undefined_properties.log")

set (CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard version")
set (CMAKE_CXX_STANDARD_REQUIRED ON CACHE INTERNAL "")

set (CMAKE_CXX_VISIBILITY_PRESET hidden CACHE INTERNAL "")
set (CMAKE_VISIBILITY_INLINES_HIDDEN YES CACHE INTERNAL "")

set_property (GLOBAL PROPERTY USE_FOLDERS YES)
set_property (GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "Targets")

set (CMAKE_SUPPRESS_REGENERATION   TRUE CACHE INTERNAL "")

set (ENV{CMAKE_EXPORT_COMPILE_COMMANDS} TRUE)
set (CMAKE_EXPORT_COMPILE_COMMANDS TRUE CACHE INTERNAL "")

if (NOT DEFINED ENV{CMAKE_INSTALL_MODE})
	set (ENV{CMAKE_INSTALL_MODE} ABS_SYMLINK_OR_COPY)
endif()
