LOG_XTN := log

CONFIG_LOG_FILE := $(LOGS)/config.$(LOG_XTN)
BUILD_LOG_FILE := $(LOGS)/build.$(LOG_XTN)

CONFIG_WARNINGS_LOG_FILE := $(LOGS)/config_warnings.$(LOG_XTN)
BUILD_WARNINGS_LOG_FILE := $(LOGS)/build_warnings.$(LOG_XTN)

CONFIG_ERRORS_LOG_FILE := $(LOGS)/config_errors.$(LOG_XTN)
BUILD_ERRORS_LOG_FILE := $(LOGS)/build_errors.$(LOG_XTN)

#

POST_PROCESS_LOG := $(PYTHON) $(MAKE_UTILS_DIR)/process_logs.py $(shell pwd)

$(CONFIG_WARNINGS_LOG_FILE): 
	@$(POST_PROCESS_LOG) $(CONFIG_LOG_FILE) $(CONFIG_WARNINGS_LOG_FILE) warning

$(BUILD_WARNINGS_LOG_FILE):
	@$(POST_PROCESS_LOG) $(BUILD_LOG_FILE) $(BUILD_WARNINGS_LOG_FILE) warning

$(CONFIG_ERRORS_LOG_FILE):
	@$(POST_PROCESS_LOG) $(CONFIG_LOG_FILE) $(CONFIG_ERRORS_LOG_FILE) error

$(BUILD_ERRORS_LOG_FILE):
	@$(POST_PROCESS_LOG) $(BUILD_LOG_FILE) $(BUILD_ERRORS_LOG_FILE) error

#

#
# These are the public commands

WRITE_CONFIG_LOG := 2>&1 | tee $(CONFIG_LOG_FILE) && $(MAKE) $(CONFIG_WARNINGS_LOG_FILE) && $(MAKE) $(CONFIG_ERRORS_LOG_FILE)

WRITE_BUILD_LOG := 2>&1 | tee $(BUILD_LOG_FILE) && $(MAKE) $(BUILD_WARNINGS_LOG_FILE) && $(MAKE) $(BUILD_ERRORS_LOG_FILE)
