LOG_XTN := log

CONFIG_LOG := config
BUILD_LOG := build
WARNINGS_LOG := warnings
ERRORS_LOG := errors

CONFIG_LOG_FILE := $(LOGS)/$(CONFIG_LOG).$(LOG_XTN)
BUILD_LOG_FILE := $(LOGS)/$(BUILD_LOG).$(LOG_XTN)

CONFIG_WARNINGS_LOG_FILE := $(LOGS)/$(CONFIG_LOG)_$(WARNINGS_LOG).$(LOG_XTN)
BUILD_WARNINGS_LOG_FILE := $(LOGS)/$(BUILD_LOG)_$(WARNINGS_LOG).$(LOG_XTN)

CONFIG_ERRORS_LOG_FILE := $(LOGS)/$(CONFIG_LOG)_$(ERRORS_LOG).$(LOG_XTN)
BUILD_ERRORS_LOG_FILE := $(LOGS)/$(BUILD_LOG)_$(ERRORS_LOG).$(LOG_XTN)

#

LOG_POST_PROC_SCRIPT := $(MAKE_UTILS_DIR)/process_logs.py

POST_PROCESS_LOG := $(PYTHON) $(LOG_POST_PROC_SCRIPT) $(shell pwd)

$(CONFIG_WARNINGS_LOG_FILE): $(CONFIG_LOG_FILE) $(LOG_POST_PROC_SCRIPT)
	@$(POST_PROCESS_LOG) $(CONFIG_LOG_FILE) $(CONFIG_WARNINGS_LOG_FILE) warning

$(BUILD_WARNINGS_LOG_FILE): $(BUILD_LOG_FILE) $(LOG_POST_PROC_SCRIPT)
	@$(POST_PROCESS_LOG) $(BUILD_LOG_FILE) $(BUILD_WARNINGS_LOG_FILE) warning

$(CONFIG_ERRORS_LOG_FILE): $(CONFIG_LOG_FILE) $(LOG_POST_PROC_SCRIPT)
	@$(POST_PROCESS_LOG) $(CONFIG_LOG_FILE) $(CONFIG_ERRORS_LOG_FILE) error

$(BUILD_ERRORS_LOG_FILE): $(BUILD_LOG_FILE) $(LOG_POST_PROC_SCRIPT)
	@$(POST_PROCESS_LOG) $(BUILD_LOG_FILE) $(BUILD_ERRORS_LOG_FILE) error

#

#
# These are the public commands

WRITE_CONFIG_LOG := 2>&1 | tee $(CONFIG_LOG_FILE) && $(MAKE) $(CONFIG_WARNINGS_LOG_FILE) && $(MAKE) $(CONFIG_ERRORS_LOG_FILE)

WRITE_BUILD_LOG := 2>&1 | tee $(BUILD_LOG_FILE) && $(MAKE) $(BUILD_WARNINGS_LOG_FILE) && $(MAKE) $(BUILD_ERRORS_LOG_FILE)
