MAKE_UTILS_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

include $(MAKE_UTILS_DIR)/native/Makefile
include $(MAKE_UTILS_DIR)/basic_settings.make
include $(MAKE_UTILS_DIR)/targets.make
include $(MAKE_UTILS_DIR)/git.make