SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

include $(SELF_DIR)native/Makefile
include $(SELF_DIR)basic_settings.make
include $(SELF_DIR)targets.make
include $(SELF_DIR)git.make
include $(SELF_DIR)cmake.make