name: Docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Run script
      shell: bash
      run: export GH_REPO_TOKEN=${{ secrets.ACCESS_TOKEN }} && bash doxygen/publish_docs.sh
