name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:

  build:

    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Run script
      shell: bash
      run: bash doxygen/publish_docs.sh
