name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Log in to Docker
      uses: docker/login-action@v1
      with:
        username: benvining
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Run script
      shell: bash
      run: bash .github/publish_docker.sh
