name: Docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive

    - name: Install deps
      uses: benthevining/DepsInstaller@v0.2.0-alpha
      with:
        depfile_path: '$(pwd)/Depsfile'
        category: 'Docs'

    - name: Run script
      shell: bash
      run: export GH_REPO_TOKEN=${{ secrets.ACCESS_TOKEN }} && bash .github/publish_docs.sh
