name: Docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive

    - name: Install deps
      shell: bash
      run: bash util/install_deps/install_deps.sh

    - name: Run script
      shell: bash
      run: python3 .github/publish_docs.py ${{ secrets.ACCESS_TOKEN }}
