name: Trigger update of remote submodule inclusions

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "00 00 * * 1"

jobs:

  send-repository-dispatch:

    runs-on: ubuntu-latest

    steps:

      - name: Update the Imogen repo's copy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: benthevining/imogen
          event-type: update_submodules

      - name: Update the Pitch Detector repo's copy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: benthevining/Pitch-detector
          event-type: update_submodules

      - name: Update the Pitch Detector Tester App repo's copy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: benthevining/pitch-detector-tester
          event-type: update_submodules
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: benthevining/new-juce-project-template
          event-type: update_submodules
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: benthevining/audio-fifo-tester
          event-type: update_submodules
